### ISSUE TITLE
Unrestricted access from local network

### ISSUE THREAD

**Issue by jangeador** [dperson/openvpn-client#110]
I was able to get the containers working using the instructions. I am currently using `sabnbzd` and `radarr`. I can access the web interface for both, however when I try to add `sabnzbd` as a downloader for `radarr` it fails. I was wondering if there was a way for this container to implement a `local_network` feature which would allow unrestricted access the way this other container does: https://github.com/rickscherer/docker-transmission-sabnzbd-openvpn/blob/master/openvpn/start.sh

Here is my `docker-compose.yml` file that works other than that crucial part:

```yaml
version: '3.3'
services:
  vpn:
    image: dperson/openvpn-client
    container_name: ovpn_client
    cap_add:
      - net_admin
    env_file:
      - .env
    networks:
      - default
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - ~/.config/vpn/torguard:/vpn
    ports:
      - 8080:8080
      - 9090:9090
      - 7878:7878
  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd
    depends_on:
      - vpn
    restart: unless-stopped
    network_mode: "service:vpn"
    env_file:
      - .env
    volumes:
      - ~/.config/sabnzbd:/config
      - /data/media/completed:/downloads
      - /data/media/downloading:/incomplete-downloads
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    depends_on:
      - sabnzbd
    env_file:
      - .env
    network_mode: "service:vpn"
    volumes:
      - ~/.config/radarr:/config
      - /data/media/movies:/movies
      - /data/media/completed:/downloads
  web:                                                        
    image: dperson/nginx
    container_name: web_vpn_proxy                                      
    depends_on:                                               
      - sabnzbd                                              
    env_file:                                                 
      - .env                                                  
    links:                                                    
      - vpn:sabnzbd
      - vpn:radarr                                         
    networks:                                                 
      - default                                               
    ports:                                                    
      - "80:80"                                               
      - "443:443"                                             
    read_only: true                                           
    tmpfs:                                                    
      - /run                                                  
      - /tmp                                                  
      - /var/cache/nginx                                      
    restart: unless-stopped                                   
    stdin_open: true                                          
    tty: true                                                 
    command: -w "http://sabnzbd:8080;/sabnzbd" -w "http://radarr:7878;/radarr" 
networks:
  default:
```
