### ISSUE TITLE
Usage with docker compose & links

### ISSUE THREAD

**Issue by kierr** [dperson/openvpn-client#12]
Solved. No links required with net container, it's all done automatically.

**Comment by johnny2678** [comment]
I didn't want to open up a new issue, since this is almost certainly user error, but how exactly do you PROXY multiple sites with `docker-compose`?

With `docker run`:
```
- w "http://site1:123;/site1"
- w "http://site2:456;/site2"
```
works just fine

With `docker-compose`, I have tried:
```
dweb:
  image: dperson/nginx
  ports:
  - "80:80"
  - "443:443"
  environment:
  - PROXY=http://site1:123;/site1
  - PROXY=http://site2:456;/site2
```
Only the last one works, or:
```
  environment:
    PROXY:
      -http://site1:123;/site1
      -http://site2:456;/site2
```
doesn't compile.  Also tried nixing `environment` vars and trying to invoke with `command`:
```
dweb:
  image: dperson/nginx
  ports:
  - "80:80"
  - "443:443"
  command: -w "http://site1:123;/site1" -w "http://site2:456/site2"
```
but no luck.

Any pointers? thx!

**Comment by dperson** [comment]
Yes, you can only set an environment variable once. I use the `command` method myself as well. In your example there is a typo in the second `-w` it should be `"http://site2:456;/site2"`. Hope that helps.

**Comment by johnny2678** [comment]
Thanks for the response.  You're right about the typo... unfortunately my yml is correct, I just mistyped in github.

Will give it another go... if you have a second, could you post a working docker-compose.yml that proxies multiple sites?

Also, no `links` required, correct?

**Comment by johnny2678** [comment]
ok, after adding `links`, the proxy works. I forgot to mention that I'm also running your openvpn-client and the first post in this bug report threw me off track.

> Solved. No links required with net container, it's all done automatically.

final docker-compose.yml syntax:
```
dweb:
  image: dperson/nginx
  ports:
  - "80:80"
  - "443:443"
  links:
  - vpn:site1
  - vpn:site2
  command: -w "http://site1:123;/site1" -w "http://site2:456;/site2"
```

**Comment by dperson** [comment]
Ah, yes I have the links in my config as well, glad you spotted it.

**Comment by ChrisWeiss** [comment]
@johnny2678 - Can you share your VPN and 'site1' docker-compose entries? I'm trying to do this myself in docker-compose and am having issues with getting the network routing functioning correctly.

**Comment by johnny2678** [comment]
Here's my scrubbed config for VPN, reverse proxy, site1, and site2. Hope it helps:

```
version: '2'
services:
 vpn:
  container_name: vpn
  image: dperson/openvpn-client
  restart: unless-stopped
  cap_add:
   - NET_ADMIN
  devices:
   - "/dev/net/tun:/dev/net/tun"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /opt/vpn/openvpn-client/vpn:/vpn
  command: -d -t "EST5EDT" -v 'my.vpn.com:my2.vpn.com;user;pass' -f -r "10.0.0.9/24"

 dweb:
  container_name: dweb
  image: dperson/nginx
  restart: unless-stopped
  volumes:
   - /etc/localtime:/etc/localtime:ro
  ports:
   - "80:80"
   - "443:443"
  links:
   - vpn:site1
   - vpn:site2
  command: -w "http://site1:8888;/site1" -w "http://site2:9999;/site2" 

 site1:
  container_name: site1
  image: docker_hub_user/container_name
  restart: unless-stopped
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /opt/site1/config:/config
  environment:
  - PUID=1000
  - PGID=115
  network_mode: "service:vpn"
  depends_on:
  - vpn

 site2:
  container_name: site2
  image: docker_hub_user/container2_name
  restart: unless-stopped
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /opt/site2/config:/config
  environment:
  - PUID=1000
  - PGID=115
  network_mode: "service:vpn"
  depends_on:
  - vpn
```

**Comment by ChrisWeiss** [comment]
I'm stumped. I'm getting access denied when trying to access any of the sites trying to proxy through the web service. 

`2017/02/04 08:38:13 [error] 60#60: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.197, server: localhost, request: "GET /site2 HTTP/1.1", upstream: "http://172.18.0.3:8001/site2", host: "dh1.local"`

When I did the inital run, docker complained that there was no network setup, so I had to manually create it:
`ERROR: Cannot create container for service vpn: network workingdir_default not found`

`docker network create workingdir_default`

Here's the relevant bits of my config (vpn settings are all in config files):

```
version: '2'
services:
  vpn:
    container_name: vpn
    volumes:
      - /var/opt/openvpn:/vpn
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - "NET_ADMIN"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Los_Angeles
    image: dperson/openvpn-client
  web:
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    links:
      - vpn:site1
      - vpn:site3
      - vpn:site2
    command: -w "http://site2:8001;/site2" -w "http://site1:8002;/site1" -w "http://site3:8003;/site3"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Los_Angeles
    image: dperson/nginx
  site3:
    container_name: site3
    volumes:
      - /var/opt/site3/:/config
    depends_on:
      - vpn
    network_mode: "service:vpn"
    environment:
     - PGID=1000
     - PUID=1000
     - TZ=America/Los_Angeles
    image: linuxserver/site3
```
