### ISSUE TITLE
ERROR: VPN CA cert missing!

### ISSUE THREAD

**Issue by Shinoby1992** [dperson/openvpn-client#121]
I could run this docker successfully LOCAL 
but, i want to use it on a server, and i downloaded the sources and created a custom folder /vpn 
in that folder is the cert file.
But changing the dockerfile
and adding:
RUN mkdir -p vpn
COPY /vpn/vpn-ca.crt /vpn
 
does not work , i have to create the docker container with fully all files included , that i only need to push it to my custom repo and use it on my server. what am i doin wrong here? why can't i just add the cert file in the dockerfile and then use it?

**Comment by McGriddle** [comment]
If running via vanilla docker, I would have to add `-v /opt/docker-openvpn:/vpn -w="/vpn"` which mounts my 'vpn' folder within the docker container and sets the working directory to that folder. That folder has my .ovpn and cert file.

**Comment by Shinoby1992** [comment]
in docker swarm, how to use the network from another container? (via stack-deploy?)

**Comment by dperson** [comment]
Thanks @McGriddle, I was on a bit of a hiatus and hadn't been responding as I used to.

@Shinoby1992 I don't really use docker swarm, so that's going to have to be a separate support source. The container is working, it's just that in a different environment (swarm) connecting two containers to share a network stack works differently if it works at all.

**Comment by ahuacate** [comment]
I've got the same error and cannot find a way to solve this one. "ERROR: VPN CA cert missing!"
Heres my ovpn:
```
dev tun
fast-io
resolv-retry infinite
persist-key
#persist-tun
nobind
remote-random
remote sweden-2-ca-version-2.expressnetw.com 1195
remote netherlands-amsterdam-ca-version-2.expressnetw.com 1195
remote singapore-cbd-ca-version-2.expressnetw.com 1195
remote germany-frankfurt-1-ca-version-2.expressnetw.com 1195

pull
comp-lzo
tls-client
verify-x509-name Server name-prefix
ns-cert-type server
key-direction 1
route-method exe
route-delay 2
tun-mtu 1500
fragment 1300
mssfix 1450
verb 3
cipher AES-256-CBC
keysize 256
auth SHA512
sndbuf 524288
rcvbuf 524288
auth-user-pass /vpn/expressvpn/vpn.auth
ca /vpn/expressvpn/ca2.crt
cert /vpn/expressvpn/client.crt
key /vpn/expressvpn/client.key
tls-auth /vpn/expressvpn/ta.key
disable-occ
dhcp-option DNS 8.8.8.8
dhcp-option DNS 8.8.4.4
dhcp-option DNS 156.154.70.1
dhcp-option DNS 4.2.2.1
dhcp-option DOMAIN example.lan
# This updates the resolvconf with dns settings
script-security 2
up /etc/openvpn/up.sh
down /etc/openvpn/down.sh
```
OpenVPN connects successfully after pausing after the error 'ERROR: VPN CA cert missing!' and works perfectly. The problem is the post error pause is quite a while. 
Also I have tried a single ovpn file inclusive of the ca certs and keys and this throws multitude of errors.
My docker compose is as follows:
```
vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    restart: unless-stopped
    dns:
      - 8.8.8.8
    devices:
      - /dev/net/tun:/dev/net/tun # tun device
    working_dir: "/vpn"
    volumes:
      - /home/typhoon/docker/apps/vpn:/vpn # OpenVPN configuration
    environment:
      - TZ=Asia/Bangkok
      - DNS=8.8.8.8
      # - ROUTE=192.168.1.0/24
      - Firewall= ''
    ports:
      - 8112:8112 # port for deluge web UI to be reachable from local network
      - 58846:58846 # port for deluge web UI to be reachable from local network
      - 65088:65088 # port for deluge web UI to be reachable from local network
      - 65087:65087 # port for deluge web UI to be reachable from local network
      - 8080:8080 # port for sabnzbd web UI to be reachable from local network
      - 8989:8989 # port for sonarr web UI to be reachable from local network
      - 7878:7878 # port for radarr web UI to be reachable from local network
      - 9117:9117 # port for jackett web UI to be reachable from local network
#      - 8686:8686 # port for lidarr web UI to be reachable from local network
#      - 8096:8096 # port for emby web UI to be reachable from local network
#      - 8920:8920 # port for emby web UI to be reachable from local network     
      - 5050:5050 # port for flexget web UI to be reachable from local network
      - 9091:9091 # port for tranmission web UI to be reachable from local network
      - 51413:51413 # port for tranmission web UI to be reachable from local network
     # - 5800:5800 # port for filebot web UI to be reachable from local network
    stdin_open: true
    tty: true
```
Any ideas?
