### ISSUE TITLE
How to properly use the environment variables in docker-compose?

### ISSUE THREAD

**Issue by NQuackenboss** [dperson/openvpn-client#126]
Below is my docker-compose file for `openvpn-client`. How do I set up the firewall (block the connection if the VPN disconnects) and tell the container to use the VPN's DNS in docker-compose? Do my current environment variables do this? Can I use these envirponment variables in docker-compose because in the readme it says "only available with `docker run`." 

Also, is there any way to tell if a service is actually using the VPN connection? Is there a way to see if the `openvpn-client` container is actually connected to the VPN?

    openvpn-client:
    image: dperson/openvpn-client
    container_name: openvpn-client
    cap_add:
      - net_admin
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      - TZ=EST5EDT
      - FIREWALL=""
      - DNS=""
      - VPN=example.example.net;username;password;port
    networks:
      - vpn
      - proxy
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - /opt/openvpn-client:/vpn

**Comment by jgilfoil** [comment]
hey @NQuackenboss I too spent quite a bit of time this evening trying to work out the answer to this question(i'm pretty new to docker). I wasn't really able to figure out what was meant by the 
> ENVIRONMENT VARIABLES (only available with docker run)

section either. However I think I worked out another way to accomplish it. 

All the flags in the help output under configuration in the readme are just flags being passed as Cmd arguments to the init script openvpn.sh that is set in the dockerfile entrypoint. When you use docker run and use the flags you're essentially passing the CMD ["arg1","arg2"] functionality that would normally be set in the dockerfile. So, in order to do this via docker-compose, see this documentation (and see my example docker-compose.yml below) https://docs.docker.com/compose/compose-file/#command . 

As for DNS, this is a docker compose setting, and also not an environment variable (at least the way I did it). See below example. 

I haven't tried the VPN argument, but based on the comments in the delivered docker-compose.yml, i'm guessing it would work the same way. 

```
version: '3.4'

services:
  vpn:
    image: dperson/openvpn-client
    container_name: openvpn
    # cap_add, security_opt, and volume required for the image to function
    cap_add:
      - net_admin
    environment:
      - TZ=EST5EDT
    networks:
      - default
    dns:
      - 8.8.8.8
      - 8.8.4.4
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - /data/openvpn/vpn:/vpn
    command: ["-f", " "]
    # Put .ovpn configuration file in the /vpn directory (in "volumes:" above or
    # launch using the command line arguments, IE pick one:
    #  - ./vpn:/vpn
    # command: 'server;user;password[;port]'
```

I'm guessing something like the following might work for your vpn flag:
`command: ["-f", " ", "-v", "example.example.net;username;password;port"]`
