### ISSUE TITLE
Connect host

### ISSUE THREAD

**Issue by Schlesiger** [dperson/openvpn-client#128]
Greetings,

I am using `openvpn-client` to connect my host to the VPN with the `network_mode: host` setting and a masquerade rule to `tun0`. This setup is working. However, I'd prefer to not use `network_mode: host` and instead create a gateway to a docker network that the host can connect to. For example:

```yml
version: '3.6'

services:
  openvpn-client:
    cap_add:
    - NET_ADMIN
    command: -f ''
    depends_on:
    - bind
    - unifi
    devices:
    - "/dev/net/tun:/dev/net/tun"
    dns:
    - "8.8.8.8"
    environment:
      TZ: 'EST5EDT'
    image: dperson/openvpn-client
    networks:
      wan:
        ipv4_address: 192.168.0.3
      vpn:
        ipv4_address: 172.16.16.2
    read_only: true
    restart: unless-stopped
    stdin_open: true
    tty: true
    tmpfs:
    - /tmp
    volumes:
    - ./vpn:/vpn

networks:
  vpn:
    driver: macvlan
    driver_opts:
      parent: vpn0
    ipam:
      config:
      - subnet: 172.16.16.0/24
  wan:
    driver: macvlan
    driver_opts:
      parent: enp12s0
    ipam:
      config:
      - subnet: 192.168.0.0/24
```

Then on the host I've tried creating the `vpn0` interface with a gateway of  `172.16.16.2`

I can't figure out how to get this to work, though. Docker logs show the VPN does connect. I am assuming it's because `openvpn-client` won't route traffic; which makes sense.

It'd be a lot easier if I could somehow pass the `tun0` interface from the `openvpn-client` to the host. Or is there a better way to achieve this?
