### ISSUE TITLE
Docker Compose help: routing, firewall, dns

### ISSUE THREAD

**Issue by gurabli** [dperson/openvpn-client#143]
I managed to configure VPN and to use it for Deluge and Oscam dockers. It looks that everything is working as it should. I use Traefik for subdomain access, and I can access Deluge WebUI fine, just like Oscam.

1) I'm not sure if I did pass the FIREWALL, ROUTING and DNS variables correctly, could you please check my Docker Compose file to see if it is fine like this?

```
version: '3.4'

services:
  vpn:
    image: dperson/openvpn-client
    container_name: vpn
    # cap_add, security_opt, and volume required for the image to function
    cap_add:
      - net_admin
    ports:
      - '8888:8888'
      - "8112:8112"
      - "58846:58846"
      - "58946:58946"
    environment:
      TZ: 'Helsinki/Finland'
      ROUTE: 'xx.xxx.xxx.0/24'
      DNS: '8.8.4.4'
      FIREWALL: ''
    networks:
      - default
    read_only: false
    tmpfs:
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /vpn:/dev/net:z

  oscam:
    image: linuxserver/oscam
    container_name: oscam
    restart: on-failure
    depends_on:
      - vpn
    network_mode: "service:vpn"
    environment:
      - TZ='Helsinki/Finland'
    volumes:
      - ${USERDIR}/docker/oscam:/config
    labels:
      - "traefik.enable=true"
      - "traefik.backend=oscam"
      - "traefik.frontend.rule=Host:oscam.${DOMAINNAME}"
      - "traefik.port=8888"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=EXAMPE.COM"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

networks:
  default:
  traefik_proxy:
    external:
      name: traefik_proxy
```

2) What does the FIREWALL actually do? Is it a set of iptables to prevent any leak if connection to VPN is down? How can I check if it is enabled or not?

3) I can't connect to Deluge daemon with ThinClient, but I have exposed the port required and added routing as well. Any ideas how could I try?

Many thanks for this great container and for providing support!
