### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by AnderssonPeter** [dperson/openvpn-client#144]
`It's just a simple command line argument (-f "") to turn on the firewall, and block all outbound traffic if the VPN is down.` does that block all network connections or just the ones routed through the vpn docker container?

I got the following configuration from my VPN provider how would i use it?
```
client
dev tun

proto tcp
remote some.server.com 443 # resolves to multiple VPN servers in location

remote-cert-tls server
cipher aes-256-cbc
ncp-ciphers AES-256-GCM:AES-256-CBC:AES-128-GCM
pull

nobind
reneg-sec 432000
resolv-retry infinite

compress lzo
verb 3

persist-key
persist-tun
auth-user-pass /vpn/credentials
ca /vpn/ovpn-ca.crt
tls-auth /vpn/ovpn-tls.key 1
log /vpn/openvpn.log
script-security 2
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf
```

When i start the container with the following docker-compose i get the following errors
```
version: '3.4'
services:
  vpn:
    image: dperson/openvpn-client
    # cap_add, security_opt, and volume required for the image to function
    cap_add:
      - net_admin
    environment:
      TZ: 'EST5EDT'
    networks:
      - default
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    dns:
      - #.#.#.#
      - #.#.#.#
    volumes:
      - /dev/net:/dev/net:z
      - ./vpn-client:/vpn
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: 'openvpn.sh -d -f "" -v "some.server.com user password 443"'
```
Errors:
```bash
vpn_1  | Fatal: can't open lock file /run/xtables.lock: Read-only file system
vpn_1  | Fatal: can't open lock file /run/xtables.lock: Read-only file system
vpn_1  | Fatal: can't open lock file /run/xtables.lock: Read-only file system
vpn_1  | Fatal: can't open lock file /run/xtables.lock: Read-only file system
vpn_1  | Fatal: can't open lock file /run/xtables.lock: Read-only file system
vpn_1  | Fatal: can't open lock file /run/xtables.lock: Read-only file system
vpn_1  | Fatal: can't open lock file /run/xtables.lock: Read-only file system
vpn_1  | Fatal: can't open lock file /run/xtables.lock: Read-only file system
vpn_1  | iptables v1.6.2: invalid port/service `location' specified
vpn_1  | Try `iptables -h' or 'iptables --help' for more information.
vpn_1  | iptables v1.6.2: Port "location" does not resolve to anything.
vpn_1  |
vpn_1  | Try `iptables -h' or 'iptables --help' for more information.
vpn_1  | Fatal: can't open lock file /run/xtables.lock: Read-only file system
vpn_1  | Fatal: can't open lock file /run/xtables.lock: Read-only file system
vpn_1  | Fatal: can't open lock file /run/xtables.lock: Read-only file system
vpn_1  | Fatal: can't open lock file /run/xtables.lock: Read-only file system
vpn_1  | Fatal: can't open lock file /run/xtables.lock: Read-only file system
vpn_1  | Fatal: can't open lock file /run/xtables.lock: Read-only file system
vpn_1  | Fatal: can't open lock file /run/xtables.lock: Read-only file system
vpn_1  | Fatal: can't open lock file /run/xtables.lock: Read-only file system
vpn_1  | iptables v1.6.2: invalid port/service `location' specified
vpn_1  | Try `iptables -h' or 'iptables --help' for more information.
vpn_1  | iptables v1.6.2: Port "location" does not resolve to anything.
vpn_1  |
vpn_1  | Try `iptables -h' or 'iptables --help' for more information.
vpn_1  | /usr/bin/openvpn.sh: line 119: $2: unbound variable
```
