### ISSUE TITLE
Firewall blocking healthchecks

### ISSUE THREAD

**Issue by mackattack3k** [dperson/openvpn-client#146]
It seems like the firewall rules causes the healthchecks to fail.

If I understand correctly the health check is just `curl -L 'https://api.ipify.org'`.
I have to to the following each time the container starts:

```
bash-4.4# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             172.19.0.0/16
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             owner GID match vpn
ACCEPT     udp  --  anywhere             anywhere             owner GID match vpn
ACCEPT     all  --  anywhere             10.1.0.0/28
ACCEPT     all  --  anywhere             10.1.0.0/28
bash-4.4# curl -L 'https://api.ipify.org'
^C
bash-4.4# iptables -P OUTPUT ACCEPT
bash-4.4# curl -L 'https://api.ipify.org'
165.227.235.48bash-4.4#
```

This is my docker-compose file:
```
vpn:
    image: dperson/openvpn-client
    container_name: vpn
    cap_add:
      - net_admin
    environment:
      - TZ=${TZ}
      - ROUTE=10.1.0.0/28
    networks:
      - default
      - influx
      - hass
      - mqtt
    tmpfs:
      - /tmp
    restart: always
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - ./openvpn:/vpn
```
