### ISSUE TITLE
write UDP: Operation not permitted (code=1)

### ISSUE THREAD

**Issue by Robgd** [dperson/openvpn-client#147]
Hi,

I try to run this container on my nas synology DS218+, DSM 6.2-23739 Update 2
I get this error on logs `write UDP: Operation not permitted (code=1)`

Here is my docker-compose setup:

```
container_name: vpn
    image: dperson/openvpn-client:latest
    devices:
      - /dev/net/tun
    cap_add:
      - net_admin
    environment:
      - GROUPID=0 # default group id, for downloaded files access rights
    restart: unless-stopped
    volumes:
      - /dev/net/tun:/dev/net/tun # tun device
      - /volume1/docker/.vpn:/vpn
    ports:
      - 1194:1194/udp
      - 1198:1998/udp
    command: '-r 172.19.0.0/16 -f 80' # route local network traffic
```
I've tried to run the container on my macbook and everything work fine.
I don't know what to do :(

Thanks for help.
