### ISSUE TITLE
docker-compose DNS not being set in /etc/resolv.conf

### ISSUE THREAD

**Issue by Philiphlop** [dperson/openvpn-client#149]
I am trying to port over the docker run commands into a compose, but having problems porting over the DNS settings, they simply don't get put into /etc/resolv.conf. Any ideas where I am going wrong?

Here is the working run command I'm starting from

```
[host]$ docker run -dit \
--name vpn \
--restart=unless-stopped \
--cap-add=NET_ADMIN \
--device /dev/net/tun \
-v /data/openvpn:/vpn:z \
-p 9117:9117 \
-p 1080:1080 \
-p 9091:9091 \
--dns 8.8.8.8 \
--dns 8.8.4.4 \
-d dperson/openvpn-client -r "192.168.0.0/24" -f "" 
```

This updates the resolv.conf which is then updated by the openvpn providers DNS as expected. However, when using docker-compose, there is only the following in resolv.conf which fails to resolve the openvpn providers IP. 

```
test_vpn_1  | Sat Oct  6 14:25:10 2018 RESOLVE: Cannot resolve host address: xyz.xyz:123 (Try again)
test_vpn_1  | Sat Oct  6 14:25:15 2018 RESOLVE: Cannot resolve host address: xyz.xyz:123 (Try again)
```
```
[host]$ docker exec test_vpn_1 /bin/cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0
```
Using this docker-compose.yml

```
version: '3.4'

services:
  # ================================================================================
  #                                                                      VPN GATEWAY
  vpn:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    command: -r "192.168.0.0/24" -f "" 
    # `-r "192.168.0.0/24"` Required to allow for local breakout
    # `-f ""` Required to enable firewall (block all traffic when vpn is down)
    environment:
      PGID: 2000
      PUID: 2000
      TZ: "Europe/London"
    networks:
      - default
    dns: 
    - 8.8.8.8
    - 8.8.4.4
    ports:
      - "9117:9117" 
      - "1080:1080" 
      - "9091:9091" 
    tmpfs:
      - /tmp
    read_only: true
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    devices:
      - /dev/net/tun
    volumes:
      - /data/openvpn:/vpn

    # ovpn config file should be mapped into the /vpn folder with the name of `vpn.conf`
    # vpn.conf should reference an auth file for credentials
    # auth file should be readable by owner only

networks:
 default:
```

The host has DNS settings set successfully also, but they aren't inherited if I leave out the DNS settings. 
```
[host]$ cat /etc/resolv.conf 
nameserver 8.8.8.8
nameserver 8.8.4.4
```
