### ISSUE TITLE
Container unable to resolve host

### ISSUE THREAD

**Issue by jmctune** [dperson/openvpn-client#156]
Hello,

Ever since #154 was checked in, my container has been unable to establish a connection to my VPN provider (getting DNS lookup issues). This was working fine (and has been for over a year) until I pulled the latest docker image. This issue looks to have made DNS changes to the iptables rules.

My docker-compose:

```
  openvpn:
    container_name: ovpn
    hostname: ovpn
    image: dperson/openvpn-client:latest
    networks:
      stack:
    command: -f ""
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/docker/ovpn:/vpn
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
    healthcheck:
      test: ["CMD", "curl", "-f", "https://google.com"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
```

Error:

Wed Oct 24 01:13:28 2018 RESOLVE: Cannot resolve host address: [my-vpn-provider-hostname] (Try again)
