### ISSUE TITLE
Container status unhealthy, curl can't resolve host

### ISSUE THREAD

**Issue by trohnjavolta** [dperson/openvpn-client#167]
Hello, from my understanding this issue section on github is rather for submitting bugs than asking for help with the setup. But I read other issues where you helped people so maybe you can also help me.

I'm pretty new to docker, also I'm no linux expert.
I use dockstarter.com which is a script to install and setup docker+ containers and certain variables, as far as I understood. So maybe my setup is a bit different to others.

I have the following in my docker-compose.override.yml file:
```
vpn:
    container_name: vpn
    image: dperson/openvpn-client:armhf
    cap_add:
      - net_admin
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ:'EST5EDT'
      - DNS:'8.8.4.4'
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - /home/dluser/.docker/config/vpn:/vpn
```
In /vpn dir I have my .ovpn file. I set up a ovpn client before so I made sure to add a line for logfile dir.
Looking into log file I can confirm that the ovpn client connection is successful. So far so good.

For testing I try hydra2 container. docker-compose.override file part for hydra looks like this:
```
hydra2:
    depends_on:
    - vpn
    stdin_open: true
    tty: true
```
At first I also added `network_mode: "service:vpn"` but compose fails because a port is already specified in the .env file.
So I changed .env file, this is hydra2 part:

```
### HYDRA2
HYDRA2_ENABLED=true
HYDRA2_NETWORK_MODE=service:vpn
HYDRA2_PORT_5076=5076
```
Now in hydra2 container console I issue: curl ifconfig.io to check IP but I get:
`curl: (6) Could not resolve host: ifconfig.io
`
Same inside vpn container. And in portainer I can see that vpn container has status unhealthy.
I don't know how to troubleshoot this. Can you help me? Maybe I missed sth. crucial.
