### ISSUE TITLE
Docker Compose and AUTH_FAIL

### ISSUE THREAD

**Issue by jeliasson** [dperson/openvpn-client#168]
First off, thanks for great containers @dperson!

I have some issues using the [example docker-compose file](https://github.com/dperson/openvpn-client/blob/master/docker-compose.yml#L27), more specifically when providing a `command` for OpenVPN server, username and password. This generates the following error:
```log
ERROR: command not found: vpn.provider.com;username;password
```

#### docker-compose.yaml
```yaml
version: "3.4"  # this must match the version in docker-compose.yml
services:
  vpn:
    image: dperson/openvpn-client
    container_name: vpn
    cap_add:
      - net_admin
    read_only: true
    tmpfs:
      - /run
      - /tmp
    command: 'vpn.provider.com;username;password'
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/user/docker/config/vpn:/vpn
    environment:
      - TZ=${TZ}
    dns: 1.1.1.1

```

When instead using static files (mounted to `/vpn`), and without the `command` directive, I get `AUTH_FAILED` as error. 

#### Static files as of [openvpn.sh](https://github.com/dperson/openvpn-client/blob/master/openvpn.sh#L207) definitions. 
```bash
auth="$dir/vpn.auth"
cert_auth="$dir/vpn.cert_auth"
conf="$dir/vpn.conf"
cert="$dir/vpn-ca.crt"
```

This generates the following error:
```
WARNING: file '/vpn/vpn.cert_auth' is group or others accessible
WARNING: file '/vpn/vpn.auth' is group or others accessible
OpenVPN 2.4.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Jul  8 2018
library versions: LibreSSL 2.7.4, LZO 2.10
WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.
Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
TCP/UDP: Preserving recently used remote address: [AF_INET]123.123.123.123:1194
Socket Buffers: R=[212992->212992] S=[212992->212992]
UDP link local: (not bound)
UDP link remote: [AF_INET]123.123.123.123:1194
TLS: Initial packet from [AF_INET]123.123.123.123:1194, sid=d830e027 955170aa
WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
VERIFY OK: depth=1, C=SE, ST=X, L=Y, O=Z, OU=U, CN=Royal Swedish Beer Squadron CA, emailAddress=hostmaster@provider.com
VERIFY OK: nsCertType=SERVER
Validating certificate key usage
VERIFY KU OK
Validating certificate extended key usage
++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
VERIFY EKU OK
VERIFY OK: depth=0, C=SE, ST=X, L=Y, O=Z, CN=U, emailAddress=hostmaster@provider.com
Control Channel: TLSv1.2, cipher TLSv1/SSLv3 DHE-RSA-AES256-GCM-SHA384, 3011 bit RSA
[dukfipahngae.vpn.provider.com] Peer Connection Initiated with [AF_INET]123.123.123.123:1194
SENT CONTROL [dukfipahngae.vpn.provider.com]: 'PUSH_REQUEST' (status=1)
AUTH: Received control message: AUTH_FAILED
SIGUSR1[soft,auth-failure] received, process restarting
```

In [another project](https://github.com/GhostWriters/DockSTARTer/blob/master/compose/.apps/samba/samba.yml#L7) which using `dperson/samba`, I also have some problems providing a working `command` directive.    Any suggestions on the overall syntax would be highly appreciated.

Thanks!

**Comment by macfeaster** [comment]
The command you're looking for is `-v 'vpn.server.name;username;password'`, hence you receive an error since you never provide the `-v` flag.

**Comment by jeliasson** [comment]
@macfeaster I'll give it a shot this weekend. Thanks!

**Comment by macfeaster** [comment]
The `-v` command just generates a vpn.conf for you though, if you already have that you shouldn't need the command. I use this container without any command since the `vpn.conf` I get from my provider is fine. In your `.conf` file, have you added the `vpn.auth` file, like this?

> `auth-user-pass /vpn/vpn.auth`

(For me, I had to use absolute path for the `vpn.auth` file to be found, at least when running with docker-compose)
If you don't explicitly define the `.auth` file, OpenVPN will prompt the tty for credentials.

For this and the samba container, the command is really just whatever you put after the image name (if using `docker run`), or the value of `command:` in docker-compose. For example, I use the firewall feature so my command just looks like this:
```yaml
services:
  vpn:
    ...
    command: -f ''
```

Which is the equivalent of: `docker run -it [opts] -d dperson/openvpn-client -f ''`
