### ISSUE TITLE
Containers on the same network loses IP if VPN reconnects

### ISSUE THREAD

**Issue by alex88** [dperson/openvpn-client#170]
I'm trying to expose a VNC server on a VPN, so I've modified your docker-compose like this:

```
version: '3.4'

services:
  vpn:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - ./vpn-config:/vpn

  service1:
    image: consol/centos-xfce-vnc
    depends_on:
      - vpn
    network_mode: "service:vpn"
    restart: unless-stopped

networks:
  default:
```

On first run everything works, VPN connects and if I try to connect to the VNC server using the VPN client assigned IP I'm able to.

The problem is that my config has an inactivity timeout (same issue probably happens if the connection is briefly lost) and after a successful reconnection the linked container loses its IP and the VNC connection doesn't work anymore.

E.g.

```
$ docker-compose up
....
/sbin/ip addr add dev tun0 local 10.234.0.6 peer 10.234.0.5
....
$ docker-compose exec service1 sh
sh-4.2$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1
    link/ipip 0.0.0.0 brd 0.0.0.0
3: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN group default qlen 1
    link/tunnel6 :: brd ::
4: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 100
    link/none
    inet 10.234.0.6 peer 10.234.0.5/32 scope global tun0
       valid_lft forever preferred_lft forever
35: eth0@if36: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:12:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.18.0.2/16 brd 172.18.255.255 scope global eth0
       valid_lft forever preferred_lft forever
```

Here everything works... then inactivity timeout happens

```
vpn_1       | Sat Jan  5 02:02:18 2019 Inactivity timeout (--inactive), exiting
vpn_1       | Sat Jan  5 02:02:18 2019 SIGTERM received, sending exit notification to peer
vpn_1       | Sat Jan  5 02:02:19 2019 /sbin/ip route del 10.234.0.0/16
vpn_1       | Sat Jan  5 02:02:19 2019 /sbin/ip route del 10.234.0.1/32
vpn_1       | Sat Jan  5 02:02:19 2019 Closing TUN/TAP interface
vpn_1       | Sat Jan  5 02:02:19 2019 /sbin/ip addr del dev tun0 local 10.234.0.6 peer 10.234.0.5
vpn_1       | Sat Jan  5 02:02:19 2019 SIGTERM[soft,exit-with-notification] received, process exiting
vpn_1       | Sat Jan  5 02:02:20 2019 OpenVPN 2.4.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Jul  8 2018
.......
vpn_1       | Sat Jan  5 02:02:22 2019 /sbin/ip addr add dev tun0 local 10.234.0.6 peer 10.234.0.5
.......
vpn_1       | Sat Jan  5 02:02:22 2019 Initialization Sequence Completed
```

and the service container loses its IP

```
sh-4.2$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1
    link/ipip 0.0.0.0 brd 0.0.0.0
3: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN group default qlen 1
    link/tunnel6 :: brd ::
```

so trying to connect to the VNC server returns connection refused
