### ISSUE TITLE
Firewall NOT working when VPN is not connected

### ISSUE THREAD

**Issue by alexandery** [dperson/openvpn-client#183]
David, thanks for your work here. Appreciate it.

I've noticed that a child container is able to connect to the internet when VPN connection is not established. Obviously it connects via the host network.

I've created the following compose file for testing the issue. This helps me check for IP from Firefox container (including dns leaks, etc.).

When VPN is established - Firefox correctly uses vpn network. However when VPN is down or cannot connect (I've simulated such error using a wrong remote host in my .ovpn file) - Firefox (or any other container - I've tested other containers as well) happily accesses the internet via the host network. I've got "-f '' " argument in my command for vpn service as per instructions.

In this example I've used your nginx image, however the same error is happening without it - when I simply expose Firefox (or any other container) port via "ports" instruction in the compose file on the vpn service.

## Compose file:

```
version: '3.4'

services:
  vpn_test:
    container_name: vpn_test
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin
    restart: unless-stopped
    security_opt:
      - label:disable
    environment:
      - PUID=${PUID} # default user id, defined in .env 
      - GROUPID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    networks:
      - default
    stdin_open: true
    tty: true
    tmpfs:
      - /tmp
    devices:
      - /dev/net/tun
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - config/vpn:/vpn # OpenVPN configuration
    # route local network traffic (-r); enable firewall (-f), use VPN provider DNS resolvers (-d)
    command: -r "192.168.1.0/24" -f "" -d

  dweb:
    container_name: dweb
    image: dperson/nginx
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
      - "443:443"
    links:
      - vpn_test:firefox_vpn_test
    command: -w "http://firefox_vpn_test:5800/;/firefox_vpn_test/" 

  firefox_vpn_test:
    image: jlesage/firefox:latest
    container_name: firefox_vpn_test
    network_mode: "service:vpn_test" # run on the VPN network
    depends_on:
      - vpn_test
    environment:
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}
      - TZ=${TZ} 
    volumes:
      - ./config/firefox:/config:rw
    restart: unless-stopped
    shm_size: 2g

```
