### ISSUE TITLE
Multiple Containers Using Same Incoming Port

### ISSUE THREAD

**Issue by fangar** [dperson/openvpn-client#184]
Currently my docker compose file looks similar to this with the various service ports redirected:
```
  vpn:
    container_name: vpn
    image: dperson/openvpn-client
    restart: unless-stopped
    networks:
      - vpn_network
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    dns:
      - ${PRIMARY_DNS}
      - ${SECONDARY_DNS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_STORAGE}/openvpn-client:/vpn
      - ${DOCKER_STORAGE}/shared:/shared
    environment:
      - TZ=${TZ}
    ports:
      - 9091:9091       # transmission1
      - 9099:9099       # transmission2
      - 9090:8080       # sabnzbd
      - 9092:7878       # radarr
      - 9093:8989       # sonarr
      - 9100:5800       # firefox vpn
      - 9094:5076       # hydra
# https://docs.docker.com/compose/compose-file/#ports
    command: ' -f "" -r 192.168.20.0/24 '
```
My question: I want to add a few more containers that come in as 5800 and on the container side there is no option to change it to another port, other than the standard:
```
    ports:
      - "9095:8181"
```
Which doesn't work in conjunction with vpn. Is my only hope to switch from using ports to using a reverse proxy?
