### ISSUE TITLE
For anyone looking in the future, here's my docker-compose with deluge and nzbget

### ISSUE THREAD

**Issue by adrianocr** [dperson/openvpn-client#195]
The below docker-compose configuration uses this image to connect to expressvpn and then has deluge and nzbget connect to the vpn container and routes networking through it.

```
vpn:
    image: dperson/openvpn-client
    container_name: openvpn
    cap_add:
      - net_admin
    environment:
      TZ: 'America/New_York'
      ROUTE: 192.168.1.0/24
    networks:
      - default
    read_only: true
    ports:
      - '6789:6789' #nzbget port
      - '8112:8112' #deluge port
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net/tun:/dev/net/tun:z
      - /home/[username]/containers/vpn:/vpn #place your vpn.conf file in there, and make sure you also have a creds.txt (or similar file) with your vpn username+pass and then reference this inside your vpn.conf file. 
    
  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget
    restart: unless-stopped
    depends_on:
      - vpn
    network_mode: "service:vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - '/home/[username]/containers/nzbget/config:/config'
      - '/MediaDownloads:/downloads'

  deluge:
    container_name: deluge
    image: linuxserver/deluge
    restart: unless-stopped
    depends_on:
      - vpn
    network_mode: "service:vpn"
    environment: 
      - PUID=1000
      - PGID=974
      - TZ=America/New_York
      - UMASK_SET=000
    volumes: 
      - '/MediaDownloads:/downloads'
      - '/home/[username]/containers/deluge/config:/config

networks:
  default:
```
