### ISSUE TITLE
Configuartion problem?

### ISSUE THREAD

**Issue by blacknet76** [dperson/openvpn-client#197]
Hi to all, 

I updatetd today to the new openvpn-client version and now my deluge web frontend and proxy applications doesn't work correct anymore. This docker-compose.yml file works now over a year without any problems. 
I tested and configured now over hours but I cant find the problem. I hope anyone can help.

Problem is:
1. I can't access to the deluge frontend on 192.168.1.xx:8112 (timeout) 
2. my local forward proxy doesn't work too (Firefox Proxy 192.168.1.xx:8888)

The VPN connection works, I checked it over the bash with curl, I think the problem is the routing to the application ports.

```
version: "3.6"

services:
  vpn:
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin
    restart: unless-stopped
    networks:
      - default
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ${USERDIR}/.config/vpn:/vpn
    ports:
      - "8112:8112" # deluge
      - "8888:8888" # proxy
    command: -r "192.168.1.0/24" -f ""

  proxy:
    container_name: proxy
    image: reiz/nginx_proxy
    depends_on:
      - vpn
    restart: unless-stopped
    network_mode: service:vpn
    volumes:
      - ${USERDIR}/.config/proxy/nginx.conf:/usr/local/nginx/conf/nginx.conf

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    depends_on:
      - vpn
    restart: unless-stopped
    network_mode: "service:vpn"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/.config/deluge:/config # config files
      - ${USER_DOWN}:/downloads # download folder
```
