### ISSUE TITLE
network_mode: "service:vpn" ERROR

### ISSUE THREAD

**Issue by TheRealLouCipher** [dperson/openvpn-client#211]
Starting vpn container works fine but when I start Transmission that I want to use the network of vpn container I get the following error. Any help would be appreciated!

````ERROR: Service 'transmission' uses the network stack of service 'vpn' which is undefined.````

````docker-compose.yaml````

````
version: '3.3'

services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    environment:
      TZ: 'Europe/Stockholm'
      FIREWALL: 'true'
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - /opt/docker/vpn:/vpn


  transmission:
    image: linuxserver/transmission
    container_name: transmission
    network_mode: "service:vpn"
    depends_on:
      - vpn
    environment:
      - TZ=Europe/Stockholm
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=XXXXXXXXXX
      - PASS=XXXXXXXXXX
    volumes:
      - /opt/docker/transmission:/config
      - /home/vpn/downloads:/downloads
      - /home/vpn/downloads/.incomplete:/.incomplete
      - /home/vpn/downloads/.watch:/.watch
    ports:
      - 9092:9091
      - 51414:51413
      - 51414:51413/udp
    restart: unless-stopped
    stdin_open: true
    tty: true
````
