### ISSUE TITLE
Cannot get port forwarding working

### ISSUE THREAD

**Issue by giejay** [dperson/openvpn-client#213]
I am moving from my Asus router doing the VPN client setup to this docker image. On my Asus I just needed to execute some iptables commands, just like this image is doing and my port forwarding was working. Now I cannot seem to get a "reachable: true" response from: 

docker-compose exec vpn curl ifconfig.co/port/6881

My compose file:

```
 vpn:
        image: 'dperson/openvpn-client:armhf'
        cap_add:
            - net_admin
        networks:
            - default
        read_only: true
#        sysctl:
#            - net.ipv6.conf.all.disable_ipv6=0
        tmpfs:
            - /tmp
            - /run
        restart: unless-stopped
        environment:
            - VPNPORT=6881
#            - VPNPORT_1="6881 udp" 
            - ROUTE=192.168.2.0/24
        dns:
            - ****
        security_opt:
            - 'label:disable'
        stdin_open: true
        tty: true
        volumes:
            - '/dev/net:/dev/net:z'
            - '/home/pi/openvpn-data/:/vpn'
        ports:
            - '6881:6881'
            - '6881:6881/udp'
```

I also don't know how to specify UDP as a protocol:

```
          - VPNPORT_1="6881 udp" 
```
I tried spaces, ; : but nothing seems to work. 

As you can see, my provider is OpenVPN and I have port forwarding setup in the console of OpenVPN. Do I need to perform additional steps on my raspberry pi (also opening up iptables?) or on my router?
