### ISSUE TITLE
Unable to get routing for local access to non HTTP proxy-able ports working

### ISSUE THREAD

**Issue by Azelphur** [dperson/openvpn-client#215]
Hi,

I've been unable to get routing for local access to non HTTP proxy-able ports working - I am trying to set up deluge (which has an RPC port for thin clients, not to be confused with deluge-web).

Here is my docker compose file:

```version: '3.4'
services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client
    # cap_add, security_opt, and volume required for the image to function
    cap_add:
      - net_admin
    environment:
      TZ: 'GMT'
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - /opt/openvpn:/vpn
    # Put .ovpn configuration file in the /vpn directory (in "volumes:" above or
    # launch using the command line arguments, IE pick one:
    #  - ./vpn:/vpn
    command: '-r 192.168.1.0/24 -p 58846'
    ports:
      - 58846:58846

  # Replace "service1" with and image with an actual service you want to run
  deluge:
    container_name: deluge
    image: linuxserver/deluge
    depends_on:
      - vpn
    network_mode: "service:vpn"
    restart: unless-stopped
    volumes:
      - /storage/Torrents2:/storage/Torrents
      - /storage/Usenet2:/storage/Usenet
    environment: 
      - PUID=1000
      - PGID=1000  
      - TZ=timezone
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional

networks:
  default:
```

My openvpn config file contains redirect-gateway def1
If I try and connect to 192.168.1.10:58846, I get connection refused.

Any suggestions? Thanks :)

**Comment by Azelphur** [comment]
Managed to solve this myself, I'll leave me working results here for any future googlers:
```
version: '3.4'
services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client
    # cap_add, security_opt, and volume required for the image to function
    cap_add:
      - net_admin
    environment:
      TZ: 'GMT'
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - /opt/openvpn:/vpn
    # Put .ovpn configuration file in the /vpn directory (in "volumes:" above or
    # launch using the command line arguments, IE pick one:
    #  - ./vpn:/vpn
    command: '-r 192.168.1.0/24'
    ports:
      - 58846:58846

  # Replace "service1" with and image with an actual service you want to run
  deluge:
    container_name: deluge
    image: linuxserver/deluge
    depends_on:
      - vpn
    network_mode: "service:vpn"
    restart: unless-stopped
    volumes:
      - /storage/Torrents2:/storage/Torrents
      - /storage/Usenet2:/storage/Usenet
    environment: 
      - PUID=1000
      - PGID=1000  
      - TZ=timezone
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional

networks:
  default:
```

My mistakes were:
1) Command doesn't need the -p argument, this is for forwarding traffic coming into the VPN, not from local network
2) Deluges core.conf needs to have allow_remote set to true, otherwise it won't listen on all interfaces. This must be done while deluge isn't running (you can use `docker stop deluge` and `docker cp deluge:/config/core.conf .` then edit, then sudo docker cp core.conf deluge:/config`) - be diligent with it because deluge likes to reset the changes, and so does the container itself, if you're getting connection refused that's a good reason why.
