### ISSUE TITLE
cannot connect anymore: "UDP link local: (not bound)" (worked for several months without interruption)

### ISSUE THREAD

**Issue by plozachm** [dperson/openvpn-client#216]
I was very happy with the container (vpn server is expressvpn) but for a month now it just won't connect. I didn't not change anything on the configuration part.

```
➜  docker-media git:(master) ✗ docker-compose up vpn
Starting vpn ... done
Attaching to vpn
vpn            | Sun Oct 20 17:49:42 2019 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
vpn            | Sun Oct 20 17:49:42 2019 OpenVPN 2.4.7 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  5 2019
vpn            | Sun Oct 20 17:49:42 2019 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
vpn            | Sun Oct 20 17:49:42 2019 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.
vpn            | Sun Oct 20 17:49:42 2019 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
vpn            | Sun Oct 20 17:49:42 2019 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
vpn            | Sun Oct 20 17:49:42 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]185.217.117.158:1195
vpn            | Sun Oct 20 17:49:42 2019 Socket Buffers: R=[212992->425984] S=[212992->425984]
vpn            | Sun Oct 20 17:49:42 2019 UDP link local: (not bound)
vpn            | Sun Oct 20 17:49:42 2019 UDP link remote: [AF_INET]185.217.117.158:1195
vpn            | Sun Oct 20 17:50:42 2019 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
vpn            | Sun Oct 20 17:50:42 2019 TLS Error: TLS handshake failed
vpn            | Sun Oct 20 17:50:42 2019 SIGUSR1[soft,tls-error] received, process restarting
vpn            | Sun Oct 20 17:50:42 2019 Restart pause, 5 second(s)
vpn            | Sun Oct 20 17:50:47 2019 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.
vpn            | Sun Oct 20 17:50:47 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]185.192.69.28:1195
vpn            | Sun Oct 20 17:50:47 2019 Socket Buffers: R=[212992->425984] S=[212992->425984]
vpn            | Sun Oct 20 17:50:47 2019 UDP link local: (not bound)
vpn            | Sun Oct 20 17:50:47 2019 UDP link remote: [AF_INET]185.192.69.28:1195
```

From other open issues I tried:
```
➜  docker-media git:(master) ✗ docker exec -it vpn bash
bash-5.0# curl -L 'https://api.ipify.org'
```
no reaction....

Notice I'm using the container with docker-compose:
```
  vpn:
    image: dperson/openvpn-client
  #  sysctls:
  #    - net.ipv6.conf.all.disable_ipv6=0
    container_name: vpn
    # cap_add, security_opt, and volume required for the image to function
    cap_add:
      - net_admin
    environment:
      - TZ=Europe/Madrid
    read_only: true
    dns:
        - 8.8.8.8
    ports:
      - 6077:6077
      - 6881:6881
      - 6881:6881/udp
      - 8113:8113
      - 8989:8989
      - 8990:8990
      - 8991:8991
      - 8686:8686
      - 7878:7878
      - 7879:7879
      - 7880:7880
      - 8181:8181
      - 9117:9117
      - 6767:6767
      - 6768:6768
      - 8920:8920
      - 8096:8096
      - 34400:34400
      - 32400:32400
      - 32400:32400/udp
      - 32469:32469
      - 32469:32469/udp
      - 1900:1900/udp
    networks:
      - default
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net/tun:/dev/net/tun:z
      - /home/p/admin/etc/vpn/config:/vpn
```
