### ISSUE TITLE
Cannot connect upon restart of the container (unless .firewall is removed)

### ISSUE THREAD

**Issue by jaggel** [dperson/openvpn-client#218]
I am using the container with an ovpn file provided by unlimitedvpnapp through a docker-compose yaml file with the following contents:
```
version: "3"
services:
  vpn:
    image: dperson/openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - PUID=1024
      - PGID=101
      - TZ=Europe/Athens
      - ROUTE=192.168.1.0/24
    networks:
      - vpn
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - /volume2/docker/openvpn-client:/vpn
    ports:
      - 58846:58846
      - 58946:58946
      - 8112:8112
      - 8118:8118
      - 32820:8181
      - 32800:8989
      - 32801:9898
      - 32830:7878
      - 32850:9117
    dns:
      - 8.8.8.8
      - 8.8.4.4

  deluge:
    image: linuxserver/deluge
    network_mode: service:vpn
    depends_on:
      - vpn
    environment:
      - PUID=1024
      - PGID=101
      - TZ=Europe/Athens
    volumes:
     - /volume2/docker/deluge:/config
     - /volume2/Stripe_Tank/Transient/Deluge:/downloads
    restart: unless-stopped

networks:
  vpn:
```
The first time the container comes up correctly and connects to the provider (see logfile [1strun.txt](https://github.com/dperson/openvpn-client/files/3771502/1strun.txt) for more info). After that and upon every restart of the container the connection cannot be established (see logfile
[restart.txt](https://github.com/dperson/openvpn-client/files/3771504/restart.txt)).

The only workaround I found includes deleting the .firewall file that is being created on my config folder prior of restarting...

The problem is that I do not need (and have not specified) any firewall parameter... Only the route one I used!

Thanks in advance
