### ISSUE TITLE
Linux route add command failed

### ISSUE THREAD

**Issue by frumpymoons** [dperson/openvpn-client#229]
I have these two lines in my client.conf. The second line doesn't work.
```
route 10.0.86.0 255.255.255.0 net_gateway
route 10.255.86.0 255.255.255.0 net_gateway
```

Docker logs output
```
Tue Dec 10 20:48:30 2019 /sbin/ip route add 10.0.86.0/24 via 172.18.0.1
Tue Dec 10 20:48:30 2019 /sbin/ip route add 10.255.86.0/24 via 172.18.0.1
Tue Dec 10 20:48:30 2019 ERROR: Linux route add command failed: external program exited with error status: 2
Tue Dec 10 20:48:30 2019 Initialization Sequence Completed
RTNETLINK answers: File exists
```

docker-compose
```
  openvpn-client:
    container_name: openvpn-client
    image: dperson/openvpn-client
    restart: always
    networks:
      - internal
      - proxy
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /opt/docker/openvpn-client:/vpn
    environment: 
      - TZ=Europe/Berlin
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun:/dev/net/tun

**Comment by frumpymoons** [comment]
Adding the routes as environment variables seems to work
```
  openvpn-client:
    container_name: openvpn-client
    image: dperson/openvpn-client
    restart: always
    networks:
      - internal
      - proxy
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /opt/docker/openvpn-client:/vpn
    environment: 
      - TZ=Europe/Berlin
      - ROUTE=10.255.86.0/24
      - ROUTE=10.0.86.0/24
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun:/dev/net/tun
```

**Comment by esticle** [comment]
Thanks for this - it is somewhat confusing as the README.md says:

> NOTE: optionally supports additional variables starting with the same name, IE VPNPORT also will work for VPNPORT_2, VPNPORT_3... VPNPORT_x, etc.

Although that does not work for ROUTE, ROUTE_1, ROUTE_2, ROUTE_3, etc.
It does however work specifying ROUTE several times.

docker-compose snippit:

 ```
   cap_add:
      - net_admin
    environment:
      TZ: 'Paris/Europe'
      DNS: 'true'
      FIREWALL: '53'
      ROUTE: '192.168.99.0/24'
      ROUTE: '192.168.3.0/24'
      VPNPORT: '44000' 

```

I had no idea that specifying the same environment variable more than once would work, but does.

Thanks!
