### ISSUE TITLE
--ca fails with '/vpn/vpn-ca.crt': No such file or directory

### ISSUE THREAD

**Issue by tttice** [dperson/openvpn-client#230]
I'm trying to run openvpn client inside of a docker. I put vpn-ca.crt, vpn.conf and vpn.auth in the /vpn folder, but log reports vpn-ca.crt cannot be found.
here's the docker compose file
```
services:
    vpn:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    working_dir: "/vpn"
    volumes:
      - /dev/net:/dev/net:z
      - /home/auser/appdata/openvpn-client/vpn:/vpn
    ports:
      - "9000:9000"
```
vpn.conf was renamed from client.ovpn which was generated by an openvpn access server. I added the line auth-user-pass /vpn/vpn.auth in vpn.conf, and inside vpn.auth, I put username and password in their own lines. 
I tried changing file/directory permissions to a+rwx, and it's still not finding the ca cert.
