### ISSUE TITLE
ROUTE environment variable does not reflect documentation

### ISSUE THREAD

**Issue by esticle** [dperson/openvpn-client#232]
Hi, thanks for openvpn-client, just perfect for what I need.

Self-answered this by reading #229 but related.

README.md says:

> NOTE: optionally supports additional variables starting with the same name, IE VPNPORT also will work for VPNPORT_2, VPNPORT_3... VPNPORT_x, etc.

However, specifying ROUTE,ROUTE_2,ROUTE_3, etc. environment variables does not work.

However, specifying the ROUTE environment variable several times in my docker-compose does, my truncated docker-compose yaml:

```
    cap_add:
      - net_admin
    environment:
      TZ: 'Paris/Europe'
      DNS: 'true'
      FIREWALL: '53'
      ROUTE: '192.168.99.0/24'
      ROUTE: '192.168.3.0/24'
      VPNPORT: '44000'
```
Had no idea you could do that, but there you go.

Might be useful to update README.md indicating this, or ensure ROUTE works like VPNPORT should work.
