### ISSUE TITLE
Port Forwarding to attached containers does not work

### ISSUE THREAD

**Issue by robowraith** [dperson/openvpn-client#236]
I am trying to run a jdwonloader-container and a squid-container through the openvpn-container but am unable to get port forwarding to work.
This is my docker-compose.yml:
```
version: "3"

services:
  vpn:
    container_name: "vpn_openvpn-client"
    volumes:
      - /opt/docker/openvpn:/vpn
    dns:
      - 8.8.8.8 
    cap_add:
      - NET_ADMIN
    ports:
      - 3128:3128
      - 5800:5800
    devices:
      - '/dev/net/tun'
    command: -f '' 
    image: dperson/openvpn-client 
    restart: unless-stopped

  jdownloader-2:
    container_name: "vpn_jdownloader-2"
    depends_on:
     - vpn 
    image: jlesage/jdownloader-2
    volumes:
      - '/opt/docker/jdownloader-2:/config:rw'
      - '/srv/Install:/output:rw'
    network_mode: service:vpn
    restart: unless-stopped

    #  nginx:
    #container_name: "vpn_nginx"
    #depends_on:
    #  - vpn
    #  - jdownloader-2
    #ports:
    #    - 5800:80
    #command: -w "http://vpn:5800/;/vpn"
    #image: dperson/nginx
    #restart: unless-stopped

  squid:
    container_name: "vpn_squid"
    depends_on:
      - vpn
    volumes:
      - '/opt/docker/squid/cache:/var/spool/squid'
      - '/opt/docker/squid/squid.conf:/etc/squid/squid.conf'
    network_mode: service:vpn
    image: sameersbn/squid:3.5.27-2
    restart: unless-stopped
```

All containers are running fine and working correctly, but I am not able to reach the GUI of the jdownloader-2-container via port 5800 nor am I able to use the squid.container via port 3128. Both work correctly if not connected to the openvpn-client's network stack.
If I also integrate the listed nginx-container, I am able to reach the GUI of jdownloader-2 on Port 5800 but this is not an option for squid.
I even set the option ``redirect-gateway def1`` as stated in the documentation, although this is an openvpn-server, not -client option as far as I know.

Any idea what I have configured the wrong way?
