### ISSUE TITLE
Ports not reachable from outside host

### ISSUE THREAD

**Issue by Ineluki** [dperson/openvpn-client#237]
Great work on the container, sadly I have a problem I couldn't solve after many hours:

## The Problem
I cannot reach ports in this container from outside the host where it is running. All packages are dropped. Everything works from the same host, but from any other host in the same local network, no packets can reach inside the container.

## System Info
- docker 18.09.1
- Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
- dperson/openvpn-client   latest              b1631ee46c52

```
version: '3.4'

services:

  vpn:
    image: dperson/openvpn-client:latest
    ports:
      - 8118:8118/tcp
      - 8080:8080/tcp
    dns: 1.1.1.1
    volumes:
      - "./vpnconf/:/vpn:rw"
    cap_add:
      - NET_ADMIN
    environment:
      - DNS=1
      - FIREWALL=
    devices:
      - "/dev/net/tun:/dev/net/tun:rwm"

  proxy:
    image: splazit/privoxy-alpine:latest
    cap_add:
      - NET_ADMIN
    network_mode: "service:vpn"
    depends_on:
      - vpn
```

## Reasons already excluded
- it works if executed on the docker host: `curl -x localhost:8118 startpage.com`
- other containers are reachable from the outside (tested with nginx)
- the host has no iptables rules except the ones created by docker itself (and they are created correctly)
- it is not a problem with the privoxy container - I started a http server inside the vpn-container and it has the same problem (on port 8080)
- it is not the firewall of the container (disabled it, confirmed there are no rules up)

**Comment by gorgia** [comment]
Same problem here.
Have someone been able to solve it?

**Comment by gorgia** [comment]
I have been able to solve it.
You need to add a route for your packets to come back in the environment variables of the VPN services.
```
version: '3.4'

services:

  vpn:
    image: dperson/openvpn-client:latest
    ports:
      - 8118:8118/tcp
      - 8080:8080/tcp
    dns: 1.1.1.1
    volumes:
      - "./vpnconf/:/vpn:rw"
    cap_add:
      - NET_ADMIN
    environment:
      - DNS=1
      - ROUTE=1.1.1.0/24
    devices:
      - "/dev/net/tun:/dev/net/tun:rwm"

  proxy:
    image: splazit/privoxy-alpine:latest
    cap_add:
      - NET_ADMIN
    network_mode: "service:vpn"
    depends_on:
      - vpn
```
