### ISSUE TITLE
Can't get routing to work

### ISSUE THREAD

**Issue by 19wolf** [dperson/openvpn-client#244]
I have routing set up, and ports exposed, but I cannot access any ports behind the vpn. I am able to connect on localhost, but not from elsewhere on the network.

Compose file (minus other containers):
```
version: '3.6'
services:
  transmission:
    image: linuxserver/transmission
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
    volumes:
      - '/data/Docker/transmission:/config'
      - '/data/Media/Downloads:/downloads'
      - '/dev/null:/watch'
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=America/New_York
  vpn:
    image: dperson/openvpn-client
    #container_name: vpn
    cap_add:
      - net_admin
    environment:
      - TZ=America/New_York
      - FIREWALL
      - ROUTE=192.168.0.0/23
    dns: 1.1.1.1
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: always
    security_opt:
      - 'label:disable'
    stdin_open: true
    ports:
      - '9091:9091'
      - '8989:8989'
      - '7878:7878'
      - '9117:9117'
    tty: true
    volumes:
      - '/dev/net:/dev/net:z'
      - '/data/Docker/vpn:/vpn/'
```
```
$ ip route | awk '!/ (docker0|br-)/ && /src/ {print $1}'
default
192.168.0.0/23
192.168.0.1
```

**Comment by 19wolf** [comment]
Not sure if I changed something, but I added healthchecks and now it's working?

```
version: '3.6'
services:

  transmission:
    image: linuxserver/transmission
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
    volumes:
      - '/opt/transmission:/config'
      - '/data/Media/Downloads:/downloads'
      - '/dev/null:/watch'
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=America/New_York
    healthcheck:
      test: ["CMD", "curl", "-f", "google.com"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 60s

  vpn:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    environment:
      TZ: America/New_York
      FIREWALL: 53
      ROUTE: 192.168.0.0/23
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: always
    security_opt:
      - 'label:disable'
    stdin_open: true
    ports:
      - '9091:9091'
      - '8989:8989'
      - '7878:7878'
      - '9117:9117'
    tty: true
    volumes:
      - '/dev/net:/dev/net:z'
      - '/opt/vpn:/vpn/'
```
