### ISSUE TITLE
Allow nginx to access other containers

### ISSUE THREAD

**Issue by Niondir** [dperson/openvpn-client#252]
When the nginx is running I need to use `network_mode: "service:vpn"` to be inside the VPN network. But I would like to forward traffic to existing containers inside my "http" network. Due to network_mode I can not specify `networks`. Is there any workaround to connect the networks?

```
networks:
  default:
  http:
    external:
      name: http_default

services:
  nginx:
  # ....
    networks:
      - http
```
