### ISSUE TITLE
Errors using docker-compose.yml when removing deprecated links tags

### ISSUE THREAD

**Issue by donfmorrison** [dperson/openvpn-client#262]
Please update `docker-compose` example to replace deprecated `links:` tags with preferred alternative.

Take the example below where I have removed the `links` tags:
```yml
version: '2'
services:
  vpn:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label=disable
    devices:
      - "/dev/net:/dev/net"
    volumes:
        - './vpn:/vpn'
    restart: unless-stopped
  frontend:
    image: docker_hub_user/container_name
    depends_on:
        - vpn
    network_mode: "service:vpn"
    restart: unless-stopped
  proxy:
    image: dperson/nginx
    depends_on:
      - frontend
    ports:
      - "80:80"
      - "443:443"
    tmpfs:
      - /run
      - /tmp
      - /var/cache/nginx
    restart: unless-stopped
    command: -w "http://frontend:8888;/vpn"
```
If I ssh into the `frontend` container I can access other devices on the VPN, so the vpn client connection is working great! However, I cannot access the webpage served by `frontend` from other devices on the VPN (i.e. my computer connected via the VPN).

The error I get is `host not found in upstream "frontend" in /etc/nginx/conf.d/default.conf:51`

Can you provide some direction on an acceptable/preferred way to replace the former `links` tag? I'm using balena.io and the `links` tags are not supported since they are deprecated.

Also, I *know* I am doing it wrong in that `proxy` service, the question is: what is the proper way to do it without using `links`?
