### ISSUE TITLE
Outgoing connections broken

### ISSUE THREAD

**Issue by jkaberg** [dperson/openvpn-client#284]
As of today I'm not able to do simple curls etc from inside my container without getting connection refused, this compose is what I've used for months without problems up until today

```
  web_vpn:
    image: dperson/openvpn-client
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: '-d -f "" -p 80 -p 443 -r 172.16.0.0/12'
    security_opt:
      - label:disable
    cap_add:
      - net_admin
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /dev/net:/dev/net:z
      - ${STORAGE_DIR}/vpn:/vpn
    networks:
      - majogw
      - dmz
```

```
root@gunder:~/majo# docker-compose exec web_vpn curl -vvvv https://ifconfig.co
*   Trying 104.31.138.11:443...
* TCP_NODELAY set
* connect to 104.31.138.11 port 443 failed: Connection refused
*   Trying 104.31.139.11:443...
* TCP_NODELAY set
* connect to 104.31.139.11 port 443 failed: Connection refused
*   Trying 2606:4700:3039::681f:8b0b:443...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700:3039::681f:8b0b: Address not available
*   Trying 2606:4700:3039::681f:8a0b:443...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700:3039::681f:8a0b: Address not available
*   Trying 2606:4700:3039::681f:8b0b:443...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700:3039::681f:8b0b: Address not available
*   Trying 2606:4700:3039::681f:8a0b:443...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700:3039::681f:8a0b: Address not available
* Failed to connect to ifconfig.co port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to ifconfig.co port 443: Connection refused
root@gunder:~/majo#
```

Reading the commit messages I can't see if anything changed that would affect my setup? Connection to VPN provider is up and proper routes etc in place

**Comment by dperson** [comment]
There have been a few SNAFUs from a pull request I merged. I think that this one should be resolved now. Thanks.

**Comment by jkaberg** [comment]
@dperson Didnt solve it I'm afraid, however premoving -p 80 and/or -p 443 does make curl work again.. Iptables messed up?

**Comment by jkaberg** [comment]
So just a bad workaround for now is to checkout commit https://github.com/dperson/openvpn-client/commit/d0155e33bb227448eaea51aa5851c91c38ea02e7 and build from that, it seems that https://github.com/dperson/openvpn-client/commit/6c928a7df5cb0d115361a19d7d28d0a74ab19f35 breaks port forwarding and outbound connections on the same target port

**Comment by dperson** [comment]
Sorry about that. Great job tracking it down!

**Comment by jkaberg** [comment]
@dperson so I just bumped to latest, and same issue again. Same config as in OP, am I do something wrong?

**Comment by dperson** [comment]
@5andr0 this was the report that had me revert it the first time. I thought that we'd ironed out the bugs in #290. I don't see any problems with how he's running it, or why it's broken for him now.

**Comment by 5andr0** [comment]
@dperson 
This is interesting. This issue [#291](https://github.com/dperson/openvpn-client/issues/291) also had problems when playing around with VPNPORT or -p. I'll check it out and see what i can do

**Comment by jkaberg** [comment]
Yeah remote VPN ip exposing/port forward to a web server

**Comment by 5andr0** [comment]
@jkaberg @dperson 
https://github.com/dperson/openvpn-client/pull/293

**Comment by dperson** [comment]
@5andr0 sorry, and good catch! The change is merged!

**Comment by jkaberg** [comment]
@dperson @5andr0 Sorry to be the bearer of bad news here, but still not working (curl). Also tried with this

```
web_vpn:
    image: dperson/openvpn-client:amd64
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - FIREWALL=on
      - VPNPORT0=80
      - VPNPORT1=443
      - ROUTE0="172.16.0.0/12"
      - DNS=on
    security_opt:
      - label:disable
    cap_add:
      - net_admin
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /dev/net:/dev/net:z
      - ${STORAGE_DIR}/vpn:/vpn
    networks:
      - majogw
      - dmz
```

**Comment by 5andr0** [comment]
It's alright, the other thing had to get fixed anyway. Can you try without DNS=on ?
Is ping google.com resolving the domain ?
Can you please post `ip route` and `cat /etc/resolv.conf` (you can obfuscate your ips) and `iptables -L` + `iptables -t nat -L` when vpn is up? Are other ports working besides 80 and 443?

**Comment by jkaberg** [comment]
Sure, here you go:

```
  web_vpn:
    image: dperson/openvpn-client:amd64
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - FIREWALL=on
      - VPNPORT0=80
      - VPNPORT1=443
      - ROUTE0="172.16.0.0/12"
        #      - DNS=on
    security_opt:
      - label:disable
    cap_add:
      - net_admin
    dns:
      - 8.8.8.8
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /dev/net:/dev/net:z
      - ${STORAGE_DIR}/vpn:/vpn
    networks:
      - majogw
      - dmz
```

```
bash-5.0# ip route
0.0.0.0/1 via 45.15.16.225 dev tun0
default via 172.26.0.1 dev eth0
45.15.16.49 via 172.26.0.1 dev eth0
45.15.16.224/27 dev tun0 proto kernel scope link src 45.15.16.236
128.0.0.0/1 via 45.15.16.225 dev tun0
172.16.0.0/12 via 172.26.0.1 dev eth0
172.18.0.0/16 dev eth1 proto kernel scope link src 172.18.0.2
172.26.0.0/16 dev eth0 proto kernel scope link src 172.26.0.11
bash-5.0# cat /etc/resolv.conf
# Generated by openvpn for interface tun0
nameserver 91.231.153.2
bash-5.0# iptables -L
Chain INPUT (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  172.26.0.0/16        anywhere
ACCEPT     all  --  172.16.0.0/12        anywhere
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https

Chain FORWARD (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             172.26.0.0/16
ACCEPT     all  --  172.26.0.0/16        anywhere
ACCEPT     all  --  anywhere             172.16.0.0/12
ACCEPT     all  --  172.16.0.0/12        anywhere
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https

Chain OUTPUT (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             172.26.0.0/16
ACCEPT     tcp  --  anywhere             anywhere             owner GID match vpn
ACCEPT     udp  --  anywhere             anywhere             owner GID match vpn
ACCEPT     all  --  anywhere             127.0.0.11           owner GID match vpn
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     all  --  anywhere             172.16.0.0/12
ACCEPT     all  --  anywhere             127.0.0.11
bash-5.0# iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
DOCKER_OUTPUT  all  --  anywhere             127.0.0.11
DNAT       tcp  --  anywhere             anywhere             tcp dpt:http to:127.0.0.111:80
DNAT       tcp  --  anywhere             anywhere             tcp dpt:https to:127.0.0.111:443

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
DOCKER_POSTROUTING  all  --  anywhere             127.0.0.11
MASQUERADE  all  --  anywhere             anywhere
MASQUERADE  all  --  anywhere             anywhere

Chain DOCKER_OUTPUT (1 references)
target     prot opt source               destination
DNAT       tcp  --  anywhere             127.0.0.11           tcp dpt:domain to:127.0.0.11:41767
DNAT       udp  --  anywhere             127.0.0.11           udp dpt:domain to:127.0.0.11:36350

Chain DOCKER_POSTROUTING (1 references)
target     prot opt source               destination
SNAT       tcp  --  127.0.0.11           anywhere             tcp spt:41767 to::53
SNAT       udp  --  127.0.0.11           anywhere             udp spt:36350 to::53
bash-5.0#
```

And with DNS=on

```
bash-5.0# ip route
0.0.0.0/1 via 45.15.16.225 dev tun0
default via 172.26.0.1 dev eth0
45.15.16.49 via 172.26.0.1 dev eth0
45.15.16.224/27 dev tun0 proto kernel scope link src 45.15.16.236
128.0.0.0/1 via 45.15.16.225 dev tun0
172.16.0.0/12 via 172.26.0.1 dev eth0
172.18.0.0/16 dev eth1 proto kernel scope link src 172.18.0.2
172.26.0.0/16 dev eth0 proto kernel scope link src 172.26.0.11
bash-5.0# cat /etc/resolv.conf
# Generated by openvpn for interface tun0
nameserver 91.231.153.2
bash-5.0# iptables -L
Chain INPUT (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  172.26.0.0/16        anywhere
ACCEPT     all  --  172.16.0.0/12        anywhere
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https

Chain FORWARD (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             172.26.0.0/16
ACCEPT     all  --  172.26.0.0/16        anywhere
ACCEPT     all  --  anywhere             172.16.0.0/12
ACCEPT     all  --  172.16.0.0/12        anywhere
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https

Chain OUTPUT (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             172.26.0.0/16
ACCEPT     tcp  --  anywhere             anywhere             owner GID match vpn
ACCEPT     udp  --  anywhere             anywhere             owner GID match vpn
ACCEPT     all  --  anywhere             127.0.0.11           owner GID match vpn
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     all  --  anywhere             172.16.0.0/12
ACCEPT     all  --  anywhere             127.0.0.11
bash-5.0# iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
DOCKER_OUTPUT  all  --  anywhere             127.0.0.11
DNAT       tcp  --  anywhere             anywhere             tcp dpt:http to:127.0.0.111:80
DNAT       tcp  --  anywhere             anywhere             tcp dpt:https to:127.0.0.111:443

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
DOCKER_POSTROUTING  all  --  anywhere             127.0.0.11
MASQUERADE  all  --  anywhere             anywhere
MASQUERADE  all  --  anywhere             anywhere

Chain DOCKER_OUTPUT (1 references)
target     prot opt source               destination
DNAT       tcp  --  anywhere             127.0.0.11           tcp dpt:domain to:127.0.0.11:35693
DNAT       udp  --  anywhere             127.0.0.11           udp dpt:domain to:127.0.0.11:36760

Chain DOCKER_POSTROUTING (1 references)
target     prot opt source               destination
SNAT       tcp  --  127.0.0.11           anywhere             tcp spt:35693 to::53
SNAT       udp  --  127.0.0.11           anywhere             udp spt:36760 to::53
bash-5.0#
```

Yeah other ports are working

**Comment by 5andr0** [comment]
@jkaberg Sorry for leaving you hanging so long.
```
git clone --branch dev https://github.com/5andr0/openvpn-client.git
docker build -t ovpnclient openvpn-client
```
Then use this config:

```
  web_vpn:
    image: ovpnclient
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - FIREWALL=on
      - DNS=on
    security_opt:
      - label:disable
    cap_add:
      - net_admin
    dns:
      - 8.8.8.8
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /dev/net:/dev/net:z
      - ${STORAGE_DIR}/vpn:/vpn
    networks:
      - majogw
      - dmz
```

Please test my source changes without setting VPNPORTS or ROUTES (they should still work dynamically now)
`iptables -t nat -A OUTPUT` is wrong in my opinion and should be deleted. 
All that's needed for listening remotely on the vpn IP is to allow incoming connections on the tun+ or tap+ interfaces, which i added by default now. 
No forwarding / rerouting necessary.
NAT rerouting would only be necessary to route incoming connections to another IP in the network and should be done with the PREROUTING table and not the OUTPUT, which makes no sense to me and blocks outgoing connections.
The VPN should already be configured to forward the ports to the clients vpn network IP, no rerouting or anything needed!
I tested my source with the airvpn port forward feature and a private vpn server that i've set up. Listening on both work for tcp and udp!

Please report if everything works for you with my dev branch.
Then we can consider integrating the code changes to master.

**Comment by jkaberg** [comment]
Thanks for helping. Curl works, however port fowarding not working (```curl: (7) Failed to connect to x.x.x.x port 80: Connection refused```

```
  web_vpn:
    image: ovpnclient #dperson/openvpn-client:amd64
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - FIREWALL=on
        #      - VPNPORT0=80
        #      - VPNPORT1=443
        #      - ROUTE0="172.16.0.0/12"
      - DNS=on
    security_opt:
      - label:disable
    cap_add:
      - net_admin
    dns:
      - 8.8.8.8
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /dev/net:/dev/net:z
      - ${STORAGE_DIR}/vpn:/vpn
    networks:
      - majogw
      - dmz
```

```
bash-5.0# ip route
0.0.0.0/1 via 45.15.16.129 dev tun0
default via 172.26.0.1 dev eth0
45.15.16.46 via 172.26.0.1 dev eth0
45.15.16.128/27 dev tun0 proto kernel scope link src 45.15.16.141
128.0.0.0/1 via 45.15.16.129 dev tun0
172.16.0.0/12 via 172.26.0.1 dev eth0
172.18.0.0/16 dev eth1 proto kernel scope link src 172.18.0.2
172.26.0.0/16 dev eth0 proto kernel scope link src 172.26.0.3
bash-5.0# cat /etc/resolv.conf
# Generated by openvpn for interface tun0
nameserver 91.231.153.2
bash-5.0# iptables -L
Chain INPUT (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  172.26.0.0/16        anywhere
ACCEPT     all  --  172.16.0.0/12        anywhere

Chain FORWARD (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             172.26.0.0/16
ACCEPT     all  --  172.26.0.0/16        anywhere
ACCEPT     all  --  anywhere             172.16.0.0/12
ACCEPT     all  --  172.16.0.0/12        anywhere

Chain OUTPUT (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             172.26.0.0/16
ACCEPT     tcp  --  anywhere             anywhere             owner GID match vpn
ACCEPT     udp  --  anywhere             anywhere             owner GID match vpn
ACCEPT     all  --  anywhere             127.0.0.11           owner GID match vpn
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     all  --  anywhere             172.16.0.0/12
ACCEPT     all  --  anywhere             127.0.0.11
bash-5.0# iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
DOCKER_OUTPUT  all  --  anywhere             127.0.0.11

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
DOCKER_POSTROUTING  all  --  anywhere             127.0.0.11
MASQUERADE  all  --  anywhere             anywhere
MASQUERADE  all  --  anywhere             anywhere

Chain DOCKER_OUTPUT (1 references)
target     prot opt source               destination
DNAT       tcp  --  anywhere             127.0.0.11           tcp dpt:domain to:127.0.0.11:43319
DNAT       udp  --  anywhere             127.0.0.11           udp dpt:domain to:127.0.0.11:40077

Chain DOCKER_POSTROUTING (1 references)
target     prot opt source               destination
SNAT       tcp  --  127.0.0.11           anywhere             tcp spt:43319 to::53
SNAT       udp  --  127.0.0.11           anywhere             udp spt:40077 to::53
bash-5.0#
```
