### ISSUE TITLE
Adding a route instead of reverse proxy for remote access

### ISSUE THREAD

**Issue by 5andr0** [dperson/openvpn-client#287]
I want to share my route, which allows me to access any port with any protocol on the attached containers on a VPS via the remote ip. This way i don't have to use reverse proxies, especially for non-http traffic. The built-in -r option for return_routes didn't work on the internet and is obsolete with this route:

```
ip rule add from $(hostname -i) lookup 10
ip route add default via $(ip route |awk '/default/ {print $3}') table 10
```
Firewall accept rule would be
`iptables -A INPUT -d $(hostname -i) -j ACCEPT`
or inside _firewall()_  reusing $docker_network
`iptables -A INPUT -d ${docker_network} -j ACCEPT`

IPv6 should be like that:
```
ip6addr=$(ip -6 addr | grep inet6 | awk -F '[ \t]+|/' '{print $3}' | 
    grep -v ^::1 | grep -v ^fe80)
ip -6 rule add from $ip6addr lookup 10
ip -6 route add default via $(ip -6 route |awk '/default/ {print $3}') table 10
ip6tables -A INPUT -d $ip6addr -j ACCEPT 2>/dev/null
# or inside firewall() reusing $docker6_network
ip6tables -A INPUT -d ${docker6_network} -j ACCEPT 2>/dev/null
```

IPv6 not tested yet! Maybe someone else could help here?

I think this route should be added by default, but i'll leave the implementation to you. That's why i haven't created a pull request.

In the last commit you forgot to change the loopback IP for vpnportforward() to avoid conflicts with the embedded DNS and its rules.
You should change line 204 inside vpnportforward():
```
    iptables -t nat -A OUTPUT -p $protocol --dport $port -j DNAT \
                --to-destination 127.0.0.11:$port
```
to
```
    iptables -t nat -A OUTPUT -p $protocol --dport $port -j DNAT \
                --to-destination 127.0.0.111:$port
```

**Comment by dperson** [comment]
The `-r` option for return routes is about letting your local network talk to containers that are using the VPN containers network stack directly. If you want custom routing taking place I'd suggest putting the extra commands you want run in `/vpn/.firewall_cust` inside the container. It will be run when the firewall is started up.

**Comment by konwin** [comment]
> 
> 
> I want to share my route, which allows me to access any port with any protocol on the attached containers on a VPS via the remote ip. This way i don't have to use reverse proxies, especially for non-http traffic. The built-in -r option for return_routes didn't work on the internet and is obsolete with this route:
> 
> ```
> ip rule add from $(hostname -i) lookup 10
> ip route add default via $(ip route |awk '/default/ {print $3}') table 10
> ```
> 
> Firewall accept rule would be
> `iptables -A INPUT -d $(hostname -i) -j ACCEPT`
> or inside _firewall()_ reusing $docker_network
> `iptables -A INPUT -d ${docker_network} -j ACCEPT`

Could you explain this a little bit more? I really would like to use this setup on a vps where my docker containers are running, but I'm not really into that stuff to work out where the commands should go!
I tried adding
>ip rule add from $(hostname -i) lookup 10
>ip route add default via $(ip route |awk '/default/ {print $3}') table 10
>iptables -A INPUT -d $(hostname -i) -j ACCEPT
to `/vpn/.firewall_cust` but I still can't reach ports definded with the vpn-container on linked service-containers!

**Comment by 5andr0** [comment]
@konwin thanks for your interest!
custom firewall rules are not live in the hub docker image. You have to build it yourself!
I added this route as default in my dev branch, so you can pull from there:

```
git clone --branch dev https://github.com/5andr0/openvpn-client.git
docker build -t ovpnclient openvpn-client
```

then you can use the image as _ovpnclient_ instead of _dperson/openvpn-client_

Advantages:
- you don't have to set ROUTE/ROUTE6 anymore for every network because this route works for all networks (tested with 2 different local networks on local linux)
- on top of the old return_route method, this can be used on a vpn with a public IP
- reverse proxies are not required anymore - you can access the ports directly
- this is very helpful for non-http ports because you would have to setup tcp and udp reverse proxy forwarding
- less lines of code

Please let me all know if this works for you!

**Comment by dperson** [comment]
@5andr0 actually the custom rules are in the image see my message above.

**Comment by barrtailor** [comment]
To test this out, I set up a simple `whoami` container behind the vpn. I have added the following to `.firewall_cust` which is in my vpn configuration directory
```
ip rule add from $(hostname -i) lookup 10
ip route add default via $(ip route |awk '/default/ {print $3}') table 10
iptables -A INPUT -d $(hostname -i) -j ACCEPT
```
`whoami` normally uses port 80 and I have removed all other containers and services that might conflict with it on the test system. I've used nginx as a reverse proxy in the past and would like to just accesses the ports directly instead of using a reverse proxy any more.

When I go to `<IP>:80` it does not resolve. Hoping that it is something simple that I'm missing, but if @dperson or @5andr0  could take a look that would be super helpful.

For reference, here is my stripped down docker-compose file
```
version: '3.7'
services:

  vpn:
    image: dperson/openvpn-client
    container_name: vpn
    cap_add:
      - net_admin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - FIREWALL=''
    devices:
      - /dev/net/tun
    networks:
      - default
    read_only: true
    tmpfs:
      - /tmp
      - /run
# commenting out otherwise container won't start
#      - /etc
#tried adding this but didn't work either
#    ports:
#      - 80:80
    dns:
      - ${DNS1}
      - ${DNS2}
    restart: always
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - ${CONFIGDIR}/vpn:/vpn

  whoami:
    image: containous/whoami
    container_name: whoami
    depends_on:
      - vpn
    network_mode: "service:vpn"

networks:
  default:
```
