### ISSUE TITLE
write UDP: Operation not permitted (code=1) on container restart/rebuild

### ISSUE THREAD

**Issue by arpitgupta** [dperson/openvpn-client#291]
Running into an interesting issue on Synology. First time container comes up everything is fine.

If i restart the container or rebuild the container i start getting errors

```
n May  3 11:42:02 2020 write UDP: Operation not permitted (code=1)
Sun May  3 11:42:04 2020 write UDP: Operation not permitted (code=1)
Sun May  3 11:42:08 2020 write UDP: Operation not permitted (code=1)
Sun May  3 11:42:09 2020 event_wait : Interrupted system call (code=4)
Sun May  3 11:42:09 2020 SIGTERM[hard,] received, process exiting
```

If i stop the container and delete the .firewall file inside the /vpn directory and start it again it will start up fine but network does not work. If i instead delete the container, delete the `.firewall` and create it again everything works fine.

My compose file looks like

```
mvd_swiz_zrh:
    container_name: mvd_swiz_zrh
    image: dperson/openvpn-client:latest
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    restart: unless-stopped
    volumes:
      - /volume1/docker/openvpn/mvd_swiz_zrh:/vpn
    dns:
      - 192.168.1.253
      - 192.168.1.63
    environment:
      ROUTE: '192.168.1.0/24'
      TZ: 'PST8PDT'
    networks:
      macvlan:
        ipv4_address: 192.168.1.241
    ports:
      # allow me to use local dns
      - 53:53
```

Using 
```
dperson/openvpn-client         latest              ec3c71bdc0cd
```

**Comment by rayban099** [comment]
The difference I see between your config and mine is the ROUTE option.  I've configured mine to run as a command in the docker-compose file.

command: -r 192.168.20.0/25 -r 192.168.20.128/25 -r 192.168.21.2

Yours is configured as an environment variable

    environment:
      ROUTE: '192.168.1.0/24'

I'm far from an expert, but maybe if you configure it as a command instead, it will work.  Remove the .firewall files, as you said earlier.  Update the config and recreate and start the VPN container.

**Comment by arpitgupta** [comment]
using command actually made the problem worse, vpn connection would not come up at all.

**Comment by arpitgupta** [comment]
@rayban099 i had seen your issue and noticed that you had commented out the command from the compose file.

So when i comment out the ROUTES env then everything works fine. My understanding was that ROUTE/-r option was required. Can some one shed some light into if this option is needed or not?

I have confirmed without the ROUTE env or -r option all my connections are going via VPN and have the VPN IP addr. 
Here is the latest compose file i am runnig with
```
mvd_swiz_zrh:
    container_name: mvd_swiz_zrh
    image: dperson/openvpn-client:latest
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    restart: unless-stopped
    volumes:
      - /volume1/docker/openvpn/mvd_swiz_zrh:/vpn
    dns:
      - 192.168.1.253
      - 192.168.1.63
    environment:
      TZ: 'PST8PDT'
    networks:
      macvlan:
        ipv4_address: 192.168.1.241
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    ports:
      # allow me to use local dns
      - 53:53
```
