### ISSUE TITLE
Impossible to connect since recent update

### ISSUE THREAD

**Issue by mr-mental** [dperson/openvpn-client#294]
Hi there,
Since a recent update of my container, I can't connect anymore to my VPN.

```
ip6tables v1.8.3 (legacy): can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
ip6tables v1.8.3 (legacy): can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
iptables v1.8.3 (legacy): invalid port/service `true' specified
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.3 (legacy): Port "true" does not resolve to anything.
Try `iptables -h' or 'iptables --help' for more information.
+ exec sg vpn -c 'openvpn --cd /vpn --config /vpn/vpn.conf --script-security 2 --redirect-gateway def1 --auth-user-pass /vpn/vpn.auth                 '
Wed May  6 13:41:48 2020 WARNING: file '/vpn/vpn.auth' is group or others accessible
Wed May  6 13:41:48 2020 OpenVPN 2.4.8 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Feb  7 2020
Wed May  6 13:41:48 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
Wed May  6 13:41:48 2020 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Wed May  6 13:41:48 2020 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Wed May  6 13:41:48 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]89.249.65.19:1194
Wed May  6 13:41:48 2020 UDP link local: (not bound)
Wed May  6 13:41:48 2020 UDP link remote: [AF_INET]89.249.65.19:1194
Wed May  6 13:41:48 2020 write UDP: Operation not permitted (code=1)
Wed May  6 13:41:50 2020 write UDP: Operation not permitted (code=1)
Wed May  6 13:41:55 2020 write UDP: Operation not permitted (code=1)
Wed May  6 13:42:03 2020 write UDP: Operation not permitted (code=1)
Wed May  6 13:42:19 2020 write UDP: Operation not permitted (code=1)
Wed May  6 13:42:48 2020 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Wed May  6 13:42:48 2020 TLS Error: TLS handshake failed
```

Could you please assist on any changes which might be performed to make it work again?

Best

My compose file
```
version: "3"
    
services: 

  vpn:
    image: dperson/openvpn-client
    container_name: vpn
    restart: unless-stopped
    cap_add:
     - NET_ADMIN
    sysctls:
     - net.ipv6.conf.all.disable_ipv6=0
    security_opt:
     - label:disable
    environment:
     - PUID=1026
     - PGID=100
     - TZ=Europe/Paris
    networks:
     - vpn-network
    dns:
     - 84.200.69.80
     - 8.8.8.8
     - 9.9.9.9
    ports:
      - 4242:4242
      - 33367:33367
    devices:
     - /dev/net/tun:/dev/net/tun
    expose:
     - "8080"
    volumes:
     - /volume1/docker/vpn/config:/vpn
    command: '-f "" -r 192.168.0.0/24'
    healthcheck:
      test: ["CMD", "curl", "-Ss", "ifconfig.co"]
      interval: 60s
      timeout: 15s

networks:
  vpn-network:
    external:
      name: vpn-network
```
