### ISSUE TITLE
On latest image no longer able to access services using openvpn client container

### ISSUE THREAD

**Issue by arpitgupta** [dperson/openvpn-client#299]
using image `d46e8078f483`

```
bash-5.0# ip route
0.0.0.0/1 via 10.14.0.1 dev tun0 
default via 192.168.1.1 dev eth0 
10.14.0.0/16 dev tun0 proto kernel scope link src 10.14.0.11 
128.0.0.0/1 via 10.14.0.1 dev tun0 
185.65.135.152 via 192.168.1.1 dev eth0 
192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.240 
bash-5.0# iptables -L
Chain INPUT (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  192.168.1.0/24       anywhere            
ACCEPT     all  --  anywhere             14f0f63b8709        

Chain FORWARD (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             192.168.1.0/24      
ACCEPT     all  --  192.168.1.0/24       anywhere            

Chain OUTPUT (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             192.168.1.0/24      
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:h323hostcallsc
ACCEPT     udp  --  anywhere             anywhere             udp dpt:h323hostcallsc
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     all  --  anywhere             127.0.0.11 
```

I do use a macvlan network for the container so not sure if that caused some issues. But image that was built yesterday worked just fine. So changes in the newest build caused issues.

compose file
```
  mvd_sweden:
    container_name: mvd_sweden
    image: dperson/openvpn-client:latest
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    restart: unless-stopped
    volumes:
      - /mvd_sweden:/vpn
    dns:
      - 192.168.1.253
      - 192.168.1.63
    environment:
      TZ: 'PST8PDT'
      # Enable firewall so we have kill switch.
      FIREWALL: ''
    networks:
      macvlan:
        ipv4_address: 192.168.1.240
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    ports:
      # tautulli
      - "8181:8181/tcp"
    healthcheck:
      test: ["CMD-SHELL", "curl -f https://am.i.mullvad.net/connected | grep -i 'you are connected to mullvad'"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 40s
```
