### ISSUE TITLE
Inactivity timeout

### ISSUE THREAD

**Issue by mindfuucker** [dperson/openvpn-client#307]
Hi

I've been trying to use the docker container to connect to a CyberGhost VPN server. 
The VPN connection seems to work, only after a minute the container restarts. 

```
Inactivity timeout (--ping-exit), exiting
Closing socket
```

This is the log I get:
[link](https://hastebin.com/ukotidejan.sql)

Using this docker-compose file:
```
version: '3.4'

services:
  vpn:
    container_name: "vpn"
    image: dperson/openvpn-client
    # cap_add, security_opt, and volume required for the image to function
    cap_add:
      - net_admin
    environment:
      TZ: 'Europe/Amsterdam'
      VPN_AUTH: 'hidden;hidden'
      ROUTE: "192.168.1.0/24"
    networks:
      - default
    # if using '-d' or 'DNS' you can't enable the `read_only: true` option
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    ports:
      - 1080:1080
      - 8112:8112
    volumes:
      - /dev/net:/dev/net:z
      - ./vpn:/vpn
```
