### ISSUE TITLE
OpenVPN exiting due to fatal error

### ISSUE THREAD

**Issue by T3ctonic** [dperson/openvpn-client#312]
Hi there, very new to all of this so please try to excuse my lack of knowledge. So, to start off, I just wanted to run OpenVPN for transmission which I got fully working with haugene/transmission-openvpn. Then I heard it is better to just have a single VPN container and run all your other containers through that one, as I wanted to have more containers in the future.

But for the life of me I couldn't get it to work. The OpenVPN section always exits with a fatal error and just goes into a re-boot loop with the same error every time. So I hope there is somebody that will be able to help me with this issue.

Below are all the files that I think you need to work out whatever I am doing wrong.

Error Log - shortened to just one boot of OpenVPN as they were all the same
```
vpn_1 | mknod: /dev/net/tun: File exists

vpn_1 | + exec sg vpn -c 'openvpn --cd /vpn --config /vpn/Windscribe-United-Kingdom.ovpn --script-security 2 --redirect-gateway def1 --auth-user-pass /vpn/vpn.auth '

vpn_1 | Tue Jun 2 11:29:47 2020 WARNING: file '/vpn/vpn.auth' is group or others accessible

vpn_1 | Tue Jun 2 11:29:47 2020 OpenVPN 2.4.8 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Feb 7 2020

vpn_1 | Tue Jun 2 11:29:47 2020 library versions: OpenSSL 1.1.1g 21 Apr 2020, LZO 2.10

vpn_1 | Tue Jun 2 11:29:47 2020 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication

vpn_1 | Tue Jun 2 11:29:47 2020 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication

vpn_1 | Tue Jun 2 11:29:47 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]212.102.63.62:54783

vpn_1 | Tue Jun 2 11:29:47 2020 UDP link local: (not bound)

vpn_1 | Tue Jun 2 11:29:47 2020 UDP link remote: [AF_INET]212.102.63.62:54783

vpn_1 | Tue Jun 2 11:29:47 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this

vpn_1 | Tue Jun 2 11:29:47 2020 VERIFY OK: depth=1, C=CA, ST=ON, L=Toronto, O=Windscribe Limited, OU=Operations, CN=Windscribe Node CA

vpn_1 | Tue Jun 2 11:29:47 2020 VERIFY KU OK

vpn_1 | Tue Jun 2 11:29:47 2020 Validating certificate extended key usage

vpn_1 | Tue Jun 2 11:29:47 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication

vpn_1 | Tue Jun 2 11:29:47 2020 VERIFY EKU OK

vpn_1 | Tue Jun 2 11:29:47 2020 VERIFY OK: depth=0, C=CA, ST=ON, O=Windscribe Limited, OU=Operations, CN=Windscribe Node Server 4096

vpn_1 | Tue Jun 2 11:29:47 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1550'

vpn_1 | Tue Jun 2 11:29:47 2020 WARNING: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher AES-256-GCM'

vpn_1 | Tue Jun 2 11:29:47 2020 WARNING: 'auth' is used inconsistently, local='auth SHA512', remote='auth [null-digest]'

vpn_1 | Tue Jun 2 11:29:47 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA

vpn_1 | Tue Jun 2 11:29:47 2020 [Windscribe Node Server 4096] Peer Connection Initiated with [AF_INET]212.102.63.62:54783

vpn_1 | Tue Jun 2 11:29:48 2020 Data Channel: using negotiated cipher 'AES-256-GCM'

vpn_1 | Tue Jun 2 11:29:48 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key

vpn_1 | Tue Jun 2 11:29:48 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key

vpn_1 | Tue Jun 2 11:29:48 2020 ERROR: Cannot ioctl TUNSETIFF tun: Function not implemented (errno=38)

vpn_1 | Tue Jun 2 11:29:48 2020 Exiting due to fatal error
```

docker-compose.yml
```
version: '3.4'

services:
  vpn:
    image: dperson/openvpn-client
    # cap_add, security_opt, and volume required for the image to function
    cap_add:
      - net_admin
    environment:
      - TZ='Europe/London'
    networks:
      - default
    # if using '-d' or 'DNS' you can't enable the `read_only: true` option
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - 'D:\Docker\VPN\dev\net:/dev/net:z'
      - 'D:\Docker\VPN\vpn:/vpn'
    
  organizr:
    image: linuxserver/organizr
    container_name: organizr
    depends_on:
      - vpn
    network_mode: "service:vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - 'D:\Docker\Organizr:/config'
    stdin_open: true
    tty: true

    restart: unless-stopped

  web:
    image: dperson/nginx
    depends_on:
      - organizr
    environment:
      - TZ='Europe/London'
    links:
      - vpn:organizr
    networks:
      - default
    ports:
      - "9936:80"
      - "443:443"
    read_only: true
    tmpfs:
      - /run
      - /tmp
      - /var/cache/nginx
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: -w "http://organizr:8888;/organizr"
    # service1 shares the network stack of vpn. The service can by reached using
    # the name of the service as a hostname.

networks:
  default:
```

I'd also like to note that all the other containers in this stack run without any errors.

Thanks for any help

**Comment by silverbullettruck2001** [comment]
@T3ctonic, Was this issue ever resolved?

**Comment by T3ctonic** [comment]
@silverbullettruck2001 No, I just ended up using haugene/transmission-openvpn instead and just have everything not go through a vpn. I would have liked to do it the way I intended in the issue but the error I have in the OP is the closest I ever got.

**Comment by WirlyWirly** [comment]
Not sure if this will fix your issue, but you're setting up your volume mounts incorrectly, which sounds like it would cause a fatal error (at-least your mounting method never worked for me). 

```yml
    volumes:
      - 'D:\Docker\VPN\dev\net:/dev/net:z'
      - 'D:\Docker\VPN\vpn:/vpn'

    volumes:
      - /D/Docker/dev/net/:/dev/net:z
      - /D/Docker/VPN/vpn/:/vpn
```

Earlier this week I setup 2 transmission containers, both running behind this VPN, and then used nginx to be able to control them on my phone outside the the LAN (Windows 10). I was also going to use haugene/transmission-openvpn, but this seemed like a much more expandable option, and it has been since I now use the connection with other services besides transmission. I posted my docker-compose [Here](https://github.com/dperson/openvpn-client/issues/319#issuecomment-658404138) when helping out another guy with his issue. Maybe it might be able to bring you some clarification too.
