### ISSUE TITLE
No new IP address / inability to connect.

### ISSUE THREAD

**Issue by nelsonmachupa** [dperson/openvpn-client#319]
So, I've got my docker-compose file set up like below, and I am unable to get any sort of Ip address update on either of my test containers. One of them transmission, one a ddns updater (simply had it there for a sanity check)

If I change the open-vpn container to network type host, the other containers connect externally, however then there is no GUI.

I've been trying multiple ways to get all of this to work for honestly the last 3 weeks now, this image has been the closest I've gotten to getting it all set up and running without using the all-in-one container from hugine(sp?)

Either way, let me know if there is any outputs that you need to see in order to help me troubleshoot. Any help is appreciated :)
Environment: Using portioner running on open media vault running in a VM inside proxmox.

https://pastebin.com/3Lgz10Wv
^^ Used pastebin since I couldn't figure out how to get the compose file to look pretty on here lol.

**Comment by WirlyWirly** [comment]
Just yesterday, I made a docker-compose file to run this container, the nginx proxy container for remote-control, and 2 transmission containers.  I was also planning to use the haugene container, but this approach seemed much more versatile and expandable, which it already has been with my 2 transmission clients. Looks like you're trying to do the same thing, but with a single transmission container. 

I've confirmed that both my clients are behind the same VPN IP using the [Torrent IP Tool](https://torguard.net/checkmytorrentipaddress.php), that they both leech/seed just fine, and are both accessible outside the LAN using an app on my phone.

Here's my docker-compose, which will hopefully help you out some. I'd recommend watching a few [YouTube](https://www.youtube.com/watch?v=vQmk9moF8vw&list=PLRAV69dS1uWTJLvDP4Veld5F05rJAmOcp&index=21) videos that explain how services talk to each other inside docker-compose. Copying and pasting wont get you very far, it's better to know what those commands do. My compose file uses different names/ports than the README, but use whatever names you're comfortable with. I just like to be descriptive and organized.

OS: Windows  10
VPN: PIA

```yml
version: '3.7'

services:
    ----- snip -----

    # - ===== OpenVPN =====
    openvpn_service:
        image: dperson/openvpn-client
        container_name: openvpn_container
        restart: unless-stopped
        env_file: ./docker/openvpn/variables.env
        stdin_open: true
        tty: true
        cap_add:
            - NET_ADMIN
        security_opt:
            - label:disable
        tmpfs:
            - /run/
            - /tmp/
        volumes:
            - /dev/net/:/dev/net/:Z
            - ./openvpn/vpn/:/vpn/

    # - ===== NGINX =====
    nginx_service:
        image: dperson/nginx
        container_name: nginx_container
        restart: unless-stopped
        command: -w "http://openvpn_service:9091/transmission/;/transmission/" -w "http://openvpn_service:9092/transmission/;/transmission2/"
        stdin_open: true
        tty: true
        ports:
            - 15500:80
            - 443:443
        tmpfs:
            - /run/
            - /tmp/
            - /var/cache/nginx/
        depends_on:
            - transmission_service
            - transmission2_service

    # - ===== Transmission =====
    transmission_service:
        image: linuxserver/transmission
        container_name: transmission_container
        restart: unless-stopped
        env_file: ./docker/transmission/variables.env
        network_mode: service:openvpn_service
        stdin_open: true
        tty: true
        volumes:
            - ./transmission/config/:/config/
            - /B/Temp/transmission/complete:/downloads/complete/
            - /B/Temp/transmission/incomplete:/downloads/incomplete/
            - /B/Temp/transmission/watch:/watch/
            - /srv/transmission_service:/var/lib/transmission_service:Z
        depends_on:
            - openvpn_service

    # - ===== Transmission 2 =====
    transmission2_service:
        image: linuxserver/transmission
        container_name: transmission2_container
        restart: unless-stopped
        env_file: ./docker/transmission2/variables.env
        network_mode: service:openvpn_service
        stdin_open: true
        tty: true
        volumes:
            - ./transmission2/config/:/config/
            - /B/Temp/transmission2/complete:/downloads/complete/
            - /B/Temp/transmission2/incomplete:/downloads/incomplete/
            - /B/Temp/transmission2/watch:/watch/
            - /srv/transmission2_service:/var/lib/transmission2_service:Z
        depends_on:
            - openvpn_service
     
    ----- snip -----
```

You'll notice that I don't include a network option for the openvpn or nginx services. That is because docker-compose creates a default network, which all the services get added to. However, the transmission services will piggy-back the openvpn service because they use the `network_mode: service:openvpn_service` option. I also don't link two services together, that's because every service on the network can already talk among themselves by simply referencing the service name, like I did in the nginx command. You'll also see that in the nginx command I use port 9092 for the 2nd transmission container. I changed that port in the transmission settings to avoid conflicts with the first container, so I use it here too.

An important note is that the OpenVPN service wouldn't work until I added the environment variable `DNS=true`. You cant see it in the docker-compose, but I have it in a .env file.

To connect to the first transmission container on the LAN, I would go to `http://localhost:15500/transmission/web/` and to the second container `http://localhost:15500/transmission2/web/`. The `/web/` part tells transmission to open the WebUI, but if you wanted to use something like TransGUI, you would use `/rpc/` instead of `/web/`. To connect to transmission outside the LAN, I just forwarded port 15500 in my router and use my public ip address instead of localhost (If your IP changes frequently, consider using a free dynamic DNS service like [NoIP](https://www.noip.com/)).

**Comment by nelsonmachupa** [comment]
I'll give this a shot tomorrow and report back. I appreciate the reply, and that is -exactly- what I am trying to do haha :)

**Comment by nelsonmachupa** [comment]
Ok so update: I have the two transmission containers up and running. Both accessible via lan. However they are still exposing my ISP ip address & not my PIA address. (tested with a torrent ip address checker)

So a few questions:
My output of the NGINX & Openvpn container are as follows:

NGINX:
```
Generating a RSA private key
.......+++++
....................+++++
writing new private key to '/etc/nginx/ssl/privkey.pem'
-----
```

Open-vpn container:
```
Dump terminated
+ exec sg vpn -c 'openvpn --cd /vpn --config /vpn/ca_toronto-aes-128-cbc-udp-dns.ovpn --script-security 2 --redirect-gateway def1 --up /etc/openvpn/up.sh --down /etc/openvpn/down.sh                 '
Wed Jul 15 14:12:13 2020 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
Wed Jul 15 14:12:13 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
```

I'm not sure if these outputs are what is to be expected. If those mean everything started up successfully or not?

I've also noticed in my Transmission containers this error:
```
[2020-07-15 15:12:22.556] Port Forwarding State changed from "Not forwarded" to "Starting" (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/port-forwarding.c:106)
[2020-07-15 15:12:22.556] Port Forwarding State changed from "Starting" to "???" (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/port-forwarding.c:106)
```

My current compose file is:
```
version: '2'
services:

    # - ===== OpenVPN =====
    openvpn_service:
        image: dperson/openvpn-client
        container_name: openvpn_container
        restart: unless-stopped
        #env_file: ./docker/openvpn/variables.env
        stdin_open: true
        tty: true
        cap_add:
            - NET_ADMIN
        environment:
           - TZ='EST5EDT'
           - DNS=true
        security_opt:
            - label:disable
        tmpfs:
            - /run/
            - /tmp/
        volumes:
            - /dev/net/:/dev/net/:Z
            - /srv/dev-disk-by-label-Local/Docker/openvpn/vpn:/vpn

    # - ===== NGINX =====
    nginx_service:
        image: dperson/nginx
        container_name: nginx_container
        restart: unless-stopped
        command: -w "http://openvpn_service:9091/transmission/;/transmission/" -w "http://openvpn_service:9092/transmission/;/transmission2/"
        stdin_open: true
        tty: true
        ports:
            - 15500:80
            - 443:443
        tmpfs:
            - /run/
            - /tmp/
            - /var/cache/nginx/
        depends_on:
            - transmission_service
            - transmission2_service

    # - ===== Transmission =====
    transmission_service:
        image: linuxserver/transmission
        container_name: transmission_container
        restart: unless-stopped
        network_mode: service:openvpn_service
        stdin_open: true
        tty: true
        environment:
          - PUID=0
          - PGID=0
          - TZ=Europe/London
        volumes:
            - /srv/dev-disk-by-label-Local/Docker/Transmission/GithubTest1/downloads:/downloads
            - /srv/dev-disk-by-label-Local/Docker/Transmission/GithubTest1/watch:/watch
            - /srv/dev-disk-by-label-Local/Docker/Transmission/GithubTest1/config:/config
            - /srv/transmission_service:/var/lib/transmission_service:Z
        depends_on:
            - openvpn_service

    # - ===== Transmission 2 =====
    transmission2_service:
        image: linuxserver/transmission
        container_name: transmission2_container
        restart: unless-stopped
        network_mode: service:openvpn_service
        stdin_open: true
        tty: true
        environment:
          - PUID=0
          - PGID=0
          - TZ=Europe/London
        volumes:
            - /srv/dev-disk-by-label-Local/Docker/Transmission/GithubTest2/downloads:/downloads
            - /srv/dev-disk-by-label-Local/Docker/Transmission/GithubTest2/watch:/watch
            - /srv/dev-disk-by-label-Local/Docker/Transmission/GithubTest2/config:/config
            - /srv/transmission2_service:/var/lib/transmission2_service:Z
        depends_on:
            - openvpn_service
```

I should also mention I am using PIA, the CA Toronto server. My OVPN file name looks something like this:
ca_toronto-aes-128-cbc-udp-dns.ovpn

Once again thank you for your help. Like I said in the original post, this has been driving me nuts for over 3 weeks and I've done so much research on it. I'll take a look into those youtube videos you linked!

**Comment by arpitgupta** [comment]
I have the following env var set in my vpn container to enable the kill switch
```
# Enable firewall so we have kill switch.
      FIREWALL: ''
```

https://github.com/dperson/openvpn-client/blob/master/openvpn.sh#L240

What i noticed is that when i logged into my openvpn client i saw 2 networks `eth0` and `tun0` and `tun0` was the default. So when i did curl for the ip checker it would show me the vpn ip and if i had curl use `eth0` interface it would show me the ISP IP. Since the default was tun0 all the services using this container were going through the VPN. Above env var made it so that all calls via eth0 are blocked and thus would only allow outbound via tun0.

Can you check for your containers if you see multiple network interfaces and if they show the same behavior?

**Comment by nelsonmachupa** [comment]
So, after adding the firewall option, this is my compose setup for the openvpn container:
One benefit is now the Transmission client's don't connect to anything. So, that's some sort of improvement.
```
 openvpn_service:
        image: dperson/openvpn-client
        container_name: openvpn_container
        restart: unless-stopped
        #env_file: ./docker/openvpn/variables.env
        stdin_open: true
        tty: true
        cap_add:
            - NET_ADMIN
        environment:
           - TZ='EST5EDT'
           - DNS=true
           - FIREWALL=''
        security_opt:
            - label:disable
        tmpfs:
            - /run/
            - /tmp/
        volumes:
            - /dev/net/:/dev/net/:Z
            - /srv/dev-disk-by-label-Local/Docker/openvpn/vpn:/vpn
```


Now, I get some errors when starting openvpn ( I don't use IPV6 on my system so not sure how much these errors matter?)
```
WARNING: ip6tables disabled!
Run 'sudo modprobe ip6table_filter' on your host
modprobe: can't change directory to '/lib/modules': No such file or directory
modprobe: can't change directory to '/lib/modules': No such file or directory
ip6tables v1.8.4 (legacy): can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
modprobe: can't change directory to '/lib/modules': No such file or directory
modprobe: can't change directory to '/lib/modules': No such file or directory
ip6tables v1.8.4 (legacy): can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
Dump terminated
+ exec sg vpn -c 'openvpn --cd /vpn --config /vpn/ca_toronto-aes-128-cbc-udp-dns.ovpn --script-security 2 --redirect-gateway def1 --up /etc/openvpn/up.sh --down /etc/openvpn/down.sh --route-up '\''/bin/sh -c " iptables -A OUTPUT -d 127.0.0.11 -j ACCEPT"'\'' --route-pre-down '\''/bin/sh -c " iptables -D OUTPUT -d 127.0.0.11 -j ACCEPT"'\''                 '
Wed Jul 15 15:59:15 2020 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
Wed Jul 15 15:59:15 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
```

When running the ifconfig command within the container itself I get:
```
bash-5.0# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:1A:00:02  
          inet addr:172.26.0.2  Bcast:172.26.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:30 errors:0 dropped:0 overruns:0 frame:0
          TX packets:25 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:3018 (2.9 KiB)  TX bytes:1602 (1.5 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:28 errors:0 dropped:0 overruns:0 frame:0
          TX packets:28 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2910 (2.8 KiB)  TX bytes:2910 (2.8 KiB)
```

When running ip route on the host VM (Open Media Vault) I get: (xxx for privacy)
```
root@OpenMediaVault:~# ip route
default via 10.0.0.xxx dev ens18 
10.0.0.xxx/20 dev ens18 proto kernel scope link src 10.0.0.xxx 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
172.26.0.0/16 dev br-6418da21c03b proto kernel scope link src 172.26.0.1 
```
