### ISSUE TITLE
Internet connection through container under network vpn ?

### ISSUE THREAD

**Issue by RoXuS** [dperson/openvpn-client#32]
Hello !

Thx for this docker image !

I use a docker-compose file like this :

```
version: '2'                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                              
services:                                                                                                                                                                                                                                     
  vpn:                                                                                                                                                                                                                                        
    image: dperson/openvpn-client                                                                                                                                                                                                             
    container_name: vpn                                                                                                                                                                                                                       
    ports:                                                                                                                                                                                                                                    
      - "1194:1194/udp"                                                                                                                                                                                                                       
    devices:                                                                                                                                                                                                                                  
      - "/dev/net/tun"
    networks:                                                                                                                                                                                                                                 
      vpn_networks:                                                                                                                                                                                                                           
        ipv4_address: 192.168.30.2                                                                                                                                                                                                                                                                                                                                                                                                                                    
    cap_add:                                                                                                                                                                                                                                  
      - NET_ADMIN                                                                                                                                                                                                                             
    volumes:                                                                                                                                                                                                                                  
      - vpn:/vpn                                                                                                                                                                                                        
                                                                                                                                                                                                                                              
  mysql:                                                                                                                                                                                                                                      
    image: mysql:latest                                                                                                                                                                                                                       
    network_mode: "service:vpn"                                                                                                                                                                                                           
    volumes:                                                                                                                                                                                                                                  
      - gogsmysql:/var/lib/mysql                                                                                                                                                                                        
                                                                                                                                                                                                                                              
  gogs:                                                                                                                                                                                                                                       
    image: gogs/gogs                                                                                                                                                                                                                          
    network_mode: "service:vpn"                                                                                                                                                                                                               
    volumes:                                                                                                                                                                                                                                  
      - gogs:/data

  nginx-proxy:                                                                                                                                                                                                                                
    image: nginx-proxy-local                                                                                                                                                                                                                  
    container_name: nginx-proxy                                                                                                                                                                                                               
    network_mode: "service:vpn"

networks:                                                                                                                                                                                                                                     
  vpn_networks:                                                                                                                                                                                                                               
    driver: bridge                                                                                                                                                                                                                            
    ipam:                                                                                                                                                                                                                                     
      driver: default                                                                                                                                                                                                                         
      config:                                                                                                                                                                                                                                 
      - subnet: 192.168.30.0/24                                                                                                                                                                                                               
        gateway: 192.168.30.1  
```
It works very well, I have access to gogs and gogs has access to mysql. (I use the nginx to proxy pass the host to the good server `proxy_pass http://192.168.30.2:3000`).

But the containers which use the network of the vpn (mysql, gogs, nginx) haven't internet (I have tried without specific network but I have the same issue).

What is wrong with my compose ?
