### ISSUE TITLE
Container continues to display Starting or Unhealthy

### ISSUE THREAD

**Issue by BanditTech** [dperson/openvpn-client#340]
Hello, thank you for this wonderful docker image. I have been using it for a while, and the connection within the container was seemingly working. But when I do a ```sudo docker ps``` it shows me : 

Edit: Previously it was working fine, without any need to mess with the default settings. 
Password file is fine, username on one line, password on the next.
I recently needed to take down the server to replace parts, and after a month it no longer works.
My vpn has changed something it seems? They are transitioning into new servers at a new address, maybe this is the issue?
/Edit

```
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                     PORTS                                            NAMES
e330852ac418        dperson/openvpn-client:latest   "/sbin/tini -- /usr/…"   6 minutes ago       Up 6 minutes (unhealthy)   0.0.0.0:8112->8112/tcp, 0.0.0.0:9117->9117/tcp   vpn
```

At first my issue was simply renaming the ```vpn.ovpn``` to ```vpn.conf``` and at least it will seem to log into the vpn properly.

Inside the Docker log for the vpn it shows:
```
overseer@narknet:/mnt/md0/config/docker$ sudo docker logs vpn
The use of ROUTE or -r may no longer be needed, try it without!
The use of ROUTE or -r may no longer be needed, try it without!
RTNETLINK answers: Invalid argument
The use of ROUTE or -r may no longer be needed, try it without!
The use of ROUTE or -r may no longer be needed, try it without!
RTNETLINK answers: Invalid argument
Dump terminated
+ exec sg vpn -c 'openvpn --cd /vpn --config /vpn/vpn.conf --script-security 2 --redirect-gateway def1 --route-up '\''/bin/sh -c " iptables -A OUTPUT -d 127.0.0.11 -j ACCEPT"'\'' --route-pre-down '\''/bin/sh -c " iptables -D OUTPUT -d 127.0.0.11 -j ACCEPT"'\'' --auth-user-pass /vpn/vpn.auth                 '
Thu Oct 29 07:56:33 2020 WARNING: file '/vpn/vpn.auth' is group or others accessible
Thu Oct 29 07:56:33 2020 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
Thu Oct 29 07:56:33 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
Thu Oct 29 07:56:33 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Thu Oct 29 07:56:33 2020 CRL: loaded 1 CRLs from file /vpn/crl.rsa.2048.pem
Thu Oct 29 07:56:33 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]37.235.108.66:1198
Thu Oct 29 07:56:33 2020 UDP link local: (not bound)
Thu Oct 29 07:56:33 2020 UDP link remote: [AF_INET]37.235.108.66:1198
Thu Oct 29 07:56:33 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Thu Oct 29 07:56:33 2020 [losangeles406] Peer Connection Initiated with [AF_INET]37.235.108.66:1198
Thu Oct 29 07:56:34 2020 TUN/TAP device tun0 opened
Thu Oct 29 07:56:34 2020 /sbin/ip link set dev tun0 up mtu 1500
Thu Oct 29 07:56:34 2020 /sbin/ip addr add dev tun0 10.55.112.3/24 broadcast 10.55.112.255
Thu Oct 29 07:56:34 2020 Initialization Sequence Completed
```

And that is indicating that the connection is valid right?

I am not sure why my docker container status is showing as Unhealthy?

Here is my config using docker-compose:
```
version: "3.4"
services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z # tun device
      - ${ROOT}/config/vpn:/vpn # OpenVPN configuration
    security_opt:
      - label:disable
    ports:
      - 8112:8112
      - 9117:9117
    stdin_open: true
    tty: true
```

Would really appreciate some help figuring out why it remains unhealthy! :) ty for your time

**Comment by BanditTech** [comment]
Also if this is relevant, this is my configuration for the vpn.conf
```
client
dev tun
proto udp
remote us-california.privacy.network 1198
resolv-retry infinite
nobind
persist-key
persist-tun
cipher aes-128-cbc
auth sha1
tls-client
remote-cert-tls server

auth-user-pass /vpn/vpn.auth
compress
verb 1
reneg-sec 0

crl-verify /vpn/crl.rsa.2048.pem
ca /vpn/ca.rsa.2048.crt

disable-occ

keepalive 10 30 # send a ping every 10 sec and reconnect after 30 sec of unsuccessfull pings
pull-filter ignore "auth-token" # fix PIA reconnection auth error that may occur every 8 hours
```

**Comment by BanditTech** [comment]
yeah, it no longer seems to provide a network bridge, and the hosted services are not receiving/sending any data.

When I go into the deluge container, it says the ip is unavailable. 

I am going to give this another try tomorrow with everything redone from scratch, any tip on where I might need to look for the issue would be appreciated :D

**Comment by BanditTech** [comment]
still having no luck, @dperson any advice?

**Comment by BanditTech** [comment]
OK, so I searched the web for anything where other people have configured it in a different way. And I noticed I did not assign a DNS, so I gave that a try, and sure enough it works.

**Comment by georgeherby** [comment]
@BanditTech Sorry to message on closed issue, which dns did you provide and how? Was it just the normal 8.8.8.8 via `--dns=8.8.8.8` when starting the container for openvpn?

**Comment by BanditTech** [comment]
> @BanditTech Sorry to message on closed issue, which dns did you provide and how? Was it just the normal 8.8.8.8 via `--dns=8.8.8.8` when starting the container for openvpn?

I was recently playing with my docker compose and remembered reading this and never got around to responding :P so for what its worth, yes, to answer your question. for the most part:

```YAML
version: "3.4"
services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    dns:
      - 8.8.4.4
      - 8.8.8.8
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z # tun device
      - ${ROOT}/config/vpn:/vpn # config files
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    ports:
      - 8112:8112 # port for deluge web UI to be reachable from local network
      - 9117:9117 # port for Jackett UI to be reachable from local network

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${ROOT}/config/deluge:/config # config files

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${ROOT}/config/jackett:/config # config files
  ```


In order for my private tracker to recognize my downloads properly I had to download the torrent from the same IP address I initiate the download from so they both need to be behind the VPN.
