### ISSUE TITLE
Removing an old ip route

### ISSUE THREAD

**Issue by javierdlg** [dperson/openvpn-client#342]
Hi y'all,
I recently changed networks and had to change my routing option within the openvpn docker yaml and now my docker container has two routing for eth0 which prevents internet connections. 

Running `ip route` returns:
```
default via 172.23.0.1 dev eth0
172.23.0.0/16 dev eth0 proto kernel scope link src 172.23.0.2
192.168.1.0/24 via 172.23.0.1 dev eth0
192.168.50.0/24 via 172.23.0.1 dev eth0
```

My docker yaml is:
```
version: '3.4'
services:

  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    dns:
      - 8.8.8.8
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z # tun device
      - ${ROOT}/config/vpn:/vpn # OpenVPN configuration
    security_opt:
      - label:disable
    ports:
      - 8112:8112 # port for deluge web UI to be reachable from local network
    command: '-f "" -r 192.168.1.0/24' # enable firewall and route local network traffic
```

As you can see, I have the `-r 192.168.1.0/24` option where I changed the `.50` to `.1`, I believe this is what is causing issues but I am unable to remove it from the docker container, even if I restart it.

What I've tried:
- Deleting all docker images and redownloading them
- Docker-compose down and then docker-compose up -d
- Manually going into the container and removing the ip route entry
- Completely removing docker, docker cache, and all images and composing again.

But all these didn't work as the entry is still there after doing a docker-compose up
