### ISSUE TITLE
Unable to initialise new PIA container

### ISSUE THREAD

**Issue by spencerskinner99** [dperson/openvpn-client#346]
Hi, 

I have been trying to set up another vpn client to connect to a different VPN server for a different function, 

Here is my compose

```
version: '2'
services:
  vpn-huginn:
    container_name: ovpn-huginn
    hostname: ovpn-huginn
    image: dperson/openvpn-client
    restart: always
    ports:
       - "3004:3004"
    environment:
      AUTH: 'sha1'
      CIPHER: 'aes-128-cbc'  
    cap_add:
      - NET_ADMIN
    volumes:
      - /media/VMRoot/VMDocker/Docker_Configs/OVPN-huginn/vpn:/vpn
      - /dev/net/tun:/dev/net/tun
    command: -v "uk-manchester.privacy.network;USER;PASS;1198" -r 192.168.2.0/24
```

The issue im having is this

```
The use of ROUTE or -r may no longer be needed, try it without!
The use of ROUTE or -r may no longer be needed, try it without!
The use of ROUTE or -r may no longer be needed, try it without!
+ exec sg vpn -c 'openvpn --cd /vpn --config /vpn/vpn.conf --script-security 2 --redirect-gateway def1 --route-up '\''/bin/sh -c " iptables -A OUTPUT -d 127.0.0.11 -j ACCEPT"'\'' --route-pre-down '\''/bin/sh -c " iptables -D OUTPUT -d 127.0.0.11 -j ACCEPT"'\'' --route-up '\''/bin/sh -c " iptables -A OUTPUT -d 127.0.0.11 -j ACCEPT"'\'' --route-pre-down '\''/bin/sh -c " iptables -D OUTPUT -d 127.0.0.11 -j ACCEPT"'\'' --auth-user-pass /vpn/vpn.auth                 '
Fri Dec  4 13:01:56 2020 Multiple --route-up scripts defined.  The previously configured script is overridden.
Fri Dec  4 13:01:56 2020 Multiple --route-pre-down scripts defined.  The previously configured script is overridden.
Options error: --ca fails with '/vpn/vpn-ca.crt': No such file or directory (errno=2)
Fri Dec  4 13:01:56 2020 WARNING: file '/vpn/vpn.auth' is group or others accessible
Options error: Please correct these errors.
Use --help for more information.
```

I have no idea why its doing this as this is a straight copy of another compose I use with this container which works fine, have I forgotten to do something?

Thanks
