### ISSUE TITLE
IP leaks from eth0 interface, with qBittorrent

### ISSUE THREAD

**Issue by afonsoc12** [dperson/openvpn-client#352]
Hey,

So I have the container configured with the following compose file and I noticed that my real IP is being leaked, when I check it in ipleaks.net. 

To reproduce this issue, simply run this compose file and test with ipleaks.net. My VPN provider is Surfshark for what is worth.

This issue only occurs when qbittorrent tools>advanced>network interfaces is set to either all or eth0. When it is set to tun0 nothing is leaked (at least that I am aware of).
However, what I do not seem to understand is that, since qbittorrent is routed through openvpn and openvpn should not connect through eth0, how can this happen? What is the explanation?

docker-compose.yml
```yaml
version: '3'

services:
    openvpn-client:
        image: dperson/openvpn-client:latest
        container_name: openvpn-client
        cap_add:
            - net_admin
        environment:
            - GROUPID=${PGID}
            - TZ=${TZ}
            - FIREWALL=""  # Kill switch
            - DNS=1.1.1.1
            - VPN_AUTH=${OPEN_VPN_VPN_USER};${OPEN_VPN_VPN_PASS}
        security_opt:
            - label:disable
        volumes:
            - ${APPDATA_PATH}/openvpn-client:/vpn
            - /dev/net:/dev/net:z
        tmpfs:
            - /run
            - /tmp
        ports:
            - 8881:8881         # Qbittorrent
            - 6881:6881         # Qbittorrent
            - 6881:6881/udp     # Qbittorrent
        stdin_open: true
        tty: true
        #read_only: true
        network_mode: bridge
        restart: ${RESTART_POLICY}

    qbittorrent:
        image: linuxserver/qbittorrent:latest
        container_name: qbittorrent
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK_SET=022
            - WEBUI_PORT=8881
        volumes:
            - ${APPDATA_PATH}/qbittorrent:/config
            - ${DOWNLOADS_PATH}/qbittorrent:/downloads
        network_mode: "service:openvpn-client"
        restart: ${RESTART_POLICY}
   ```

**Comment by rom4nik** [comment]
In my limited testing it became apparent that as soon as GID set in both dperson/openvpn-client and linuxserver/qbittorrent matches, the latter is able to connect with tracker and peers over explicitly set network interface, bypassing the tunnel completely.

docker-compose.yml adapted from above, used in testing, which allowed leaks:

```yaml             
version: '3'
services:
    openvpn-client:
        image: dperson/openvpn-client:latest
        container_name: openvpn-client
        cap_add:
            - net_admin
        environment:
            - GROUPID=555
            - TZ=Europe/Warsaw
            - FIREWALL=""  # Kill switch
            - DNS=1.1.1.1
        security_opt:
            - label:disable
        volumes:
            - ./openvpn-client:/vpn
            - /dev/net:/dev/net:z
        tmpfs:
            - /run
            - /tmp
        ports:
            - 8881:8881         # Qbittorrent
            - 6881:6881         # Qbittorrent
            - 6881:6881/udp     # Qbittorrent
        stdin_open: true
        tty: true
        #read_only: true
        network_mode: bridge
        restart: unless-stopped

    qbittorrent:
        image: linuxserver/qbittorrent:latest
        container_name: qbittorrent
        environment:
            - PUID=1000
            - PGID=555
            - TZ=Europe/Warsaw
            - UMASK_SET=022
            - WEBUI_PORT=8881
        volumes:
            - ./qbittorrent:/config
            - ./qbittorrent:/downloads
        network_mode: "service:openvpn-client"
        restart: unless-stopped
```

Setting GROUPID different than PGID, or omitting GROUPID altogether seems to prevent connection outside tunnel, no matter if qBittorrent is bound to tun0 or some other interface.

Relevant iptables rules:

https://github.com/dperson/openvpn-client/blob/a08d70a5fd4c192390305accd5593f3348e04d4d/openvpn.sh#L79-L80

https://github.com/dperson/openvpn-client/blob/a08d70a5fd4c192390305accd5593f3348e04d4d/openvpn.sh#L105-L106

Quoting from iptables manpage:

> **owner**
> This module attempts to match various characteristics of the packet creator, for locally-generated packets. It is only valid in the OUTPUT chain, and even this some packets (such as ICMP ping responses) may have no owner, and hence never match.
> [...]
> --gid-owner groupid
>     Matches if the packet was created by a process with the given effective group id.

Combined with rules above, this essentially means any process running with the same group ID as openvpn process is allowed to pass all packets through the firewall. If you use ${PGID} to set GIDs of both openvpn and qBittorrent, this will allow the leaks to happen.
