### ISSUE TITLE
Works on macOS but not Raspberry Pi

### ISSUE THREAD

**Issue by georgeherby** [dperson/openvpn-client#369]
I have been running OpenVPN in a container to act as the network for a second container that is accessing privates hosts. On my mac it works fine. However when i run on my Raspberry Pi 4 (32 bit arm) it does not work.

## docker-compose-yaml
```
services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    restart: unless-stopped
    environment:
      TZ: 'Europe/London'
      DEFAULT_GATEWAY: 'false'
    volumes:
      - ./vpn:/vpn
    devices:
      - /dev/net/tun:/dev/net/tun
    security_opt:
      - label:disable
    ports:
      - 8755:8755
    stdin_open: true
    tty: true

  api:
    container_name: api
    build:
      context: ./
      dockerfile: DockerFile
    depends_on:
      - vpn
    environment:
      TZ: 'Europe/London'
    network_mode: "service:vpn"
    restart: unless-stopped
    stdin_open: true
    tty: true

```
Something i did notice is on my mac is it uses OpenVPN 2.4.9 ` OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020` but on the Raspberry Pi it used 2.5.0 `OpenVPN 2.5.0 armv6-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Dec 26 2020` not sure if this is related to #367 or not.

## Errors on RPi
```
 | 2071-07-05 20:17:12 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
vpn    | 2071-07-05 20:17:12 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
vpn    | 2071-07-05 20:34:24 RESOLVE: Cannot resolve host address: vpn-6.redacted:1194 (Try again)
vpn    | 2071-07-05 20:32:16 RESOLVE: Cannot resolve host address: vpn-6.redacted:1194 (Try again)
vpn    | 2071-07-05 20:35:52 Could not determine IPv4/IPv6 protocol
vpn    | 2071-07-05 20:40:32 SIGUSR1[soft,init_instance] received, process restarting
vpn    | 2071-07-05 20:38:00 Restart pause, 5 second(s)
vpn    | 2071-07-05 20:17:12 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
vpn    | 2071-07-05 20:17:12 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
vpn    | 2071-07-05 20:34:24 RESOLVE: Cannot resolve host address: vpn-2.redacted:1194 (Try again)
vpn    | 2071-07-05 20:32:16 RESOLVE: Cannot resolve host address: vpn-2.redacted:1194 (Try again)
vpn    | 2071-07-05 20:35:52 Could not determine IPv4/IPv6 protocol
vpn    | 2071-07-05 20:40:32 SIGUSR1[soft,init_instance] received, process restarting
vpn    | 2071-07-05 20:38:00 Restart pause, 5 second(s)
vpn    | 2071-07-05 20:17:12 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
vpn    | 2071-07-05 20:17:12 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
```
and
```
vpn    | 2071-05-07 15:29:20 TLS Error: TLS key negotiation failed to occur within 20 seconds (check your network connectivity)
vpn    | 2071-05-07 15:29:20 TLS Error: TLS handshake failed
vpn    | 2071-05-07 15:35:28 SIGUSR1[soft,tls-error] received, process restarting
```

**Comment by maciejzgadzaj** [comment]
I run it on Raspberry Pi 4 too (after building my own image, as explained [here](https://github.com/dperson/openvpn-client/issues/365#issuecomment-761976040)), with the following configuration:

```
  vpn:
    container_name: vpn
    # Fix for vpn's container connection error on Raspberry Pi 4:
    # RESOLVE: Cannot resolve host address: xxxxxx:xxx (Try again)
    # https://github.com/dperson/openvpn-client/issues/365#issuecomment-761976040
    image: dperson-openvpn-client:alpine3.12.3
    cap_add:
      - net_admin # required to modify network interfaces
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z # tun device
      - ${ROOT}/config/vpn:/vpn # OpenVPN configuration
    security_opt:
      - label:disable
    ports:
      - ...
    command: '-f "" -r 192.168.1.0/24' # enable firewall and route local network traffic
```
