### ISSUE TITLE
Linux route add command failed: external program exited with error status: 2

### ISSUE THREAD

**Issue by mdkeil** [dperson/openvpn-client#370]
Hello, I try to use this container with purevpn config, but getting following error:

```
+ exec sg vpn -c 'openvpn --cd /vpn --config /vpn/vpn.conf --script-security 2 --redirect-gateway def1 --auth-user-pass /vpn/vpn.auth                 '
OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
TCP/UDP: Preserving recently used remote address: [AF_INET]5.254.88.173:53
UDP link local: (not bound)
UDP link remote: [AF_INET]5.254.88.173:53
[Secure-Server] Peer Connection Initiated with [AF_INET]5.254.88.173:53
TUN/TAP device tun0 opened
RTNETLINK answers: Network unreachable
ERROR: Linux route add command failed: external program exited with error status: 2
RTNETLINK answers: Network unreachable
ERROR: Linux route add command failed: external program exited with error status: 2
RTNETLINK answers: Network unreachable
ERROR: Linux route add command failed: external program exited with error status: 2
Initialization Sequence Completed
```

**vpn.conf**
```
client
explicit-exit-notify
proto udp
remote de2-ovpn-udp.pointtoserver.com 53
dev tun
tun-mtu 1500
auth-user-pass /vpn/vpn.auth
auth-nocache
comp-lzo
;keepalive 10 60
persist-key
persist-tun
nobind
;block-outside-dns

key-direction 1
remote-cert-tls server
cipher AES-256-GCM
route-method exe
route-delay 0
route 0.0.0.0 0.0.0.0
script-security 2
```

**docker-compose**
```
 vpn-client:
    image: dperson/openvpn-client
    container_name: my-vpnclient
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Europe/Berlin
    networks:
      - default
    # if using '-d' or 'DNS' you can't enable the `read_only: true` option
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - /opt/appdata/openvpn-client:/vpn
```

any ideas?

best regards!
