### ISSUE TITLE
Tagged docker images

### ISSUE THREAD

**Issue by munnerz** [dperson/openvpn-client#40]
Currently, only :latest is tagged on Dockerhub. I run this image on a Kubernetes cluster, and as such cannot know for sure when and where a container will launch, and as such I've found that a change can be made to the Docker image that causes an incompatibility with my current configuration.

Are you able to start tagging releases onto Dockerhub, so I can consistently run this same image?

**Comment by dperson** [comment]
What kind of tags do you want?

I'm using the Debian openvpn, and really wasn't planning on supporting multiple Debian versions at the same time, and have no plans for multiple forks of the code...

**Comment by munnerz** [comment]
Ah no, I'm not bothered about the debian version being run. If possible, the openvpn version would be most ideal although I understand that can be quite difficult to do whilst also using apt to install it.

Something as simple as using the shorthand commit ref. would be great - you can then also tag as latest in case someone doesn't mind that risk. That way, at least if I do want to upgrade, I break my own container instead of one day, a container restarts and the world sets on fire :)

**Comment by dperson** [comment]
I think that you can always use the hash as a tag/label.

**Comment by munnerz** [comment]
If you create releases in repository here: https://github.com/dperson/openvpn-client/releases/new then you can use the release name as a tag, but the git commit hash is not used as a tag otherwise.

**Comment by weikinhuang** [comment]
@munnerz Do you have a guide/spec file on how to set this up on a kubernetes cluster?

**Comment by munnerz** [comment]
@weikinhuang 

I've got a deployment here you can use as a basis -

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-openvpn
  labels:
    app: nginx-openvpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-openvpn
  strategy:
    type: Recreate
  template:
    metadata:
      name: nginx-openvpn
      labels:
        app: nginx-openvpn
    spec:
      containers:
      - name: openvpn
        args:
        - -d
        image: dperson/openvpn-client
        resources:
          limits:
            cpu: 500m
            memory: 500M
          requests:
            cpu: 100m
            memory: 100M
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        volumeMounts:
        - mountPath: /vpn
          name: config
      - name: nginx
        image: nginx
      volumes:
      - configMap:
          name: openvpn-config
        name: config
```

Because all containers in a pod share a network namespace, all traffic from the nginx container will be routed via the VPN (and vice-versa).

Not sure what you plan on running alongside your VPN on a k8s cluster, but obviously the nginx container can be switched out for anything else you may need :)

In this example I've set the `privileged` flag to true - I *think* you don't need to make the container privileged. Simply adding the NET_ADMIN capability should do it (but not 100% sure, and my current version does have privileged set so I thought I should include it just in case!

Also, don't forget to include your openvpn configuration in the `openvpn-config` ConfigMap :)
