### ISSUE TITLE
openvpn + monitorrent (docker compose)

### ISSUE THREAD

**Issue by Leliil** [dperson/openvpn-client#403]
Tell me, did I do the docker compose correctly?
Or how to correctly send monitorrent traffic through openvpn ?

```
---
version: "2.4"
services:
  openvpn:
    image: dperson/openvpn-client:latest
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - "6687:6687"
    environment:
      - DNS=192.168.1.1
      - Firewall=true
      - DEFAULT_GATEWAY=false
      - tun=/dev/net/tun
      - TZ=Time/Zone
    network_mode: "bridge"
    volumes:
      - /opt/openvpn-client:/vpn
    restart: always
    privileged: true
    labels:
      autoheal: true

  monitorrent-vpn:
    image: werwolfby/monitorrent
    container_name: monitorrent-vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Time/Zone
    network_mode: "service:openvpn"
    volumes:
      - /opt/monitorrent.db:/var/www/monitorrent/monitorrent.db
      - /opt/lostfilm.py:/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py
    restart: always
    labels:
      com.centurylinklabs.watchtower.depends-on: openvpn
      autoheal: true
    depends_on:
      openvpn:
        condition: service_started
```
