### ISSUE TITLE
SIGTERM[soft,exit-with-notification] received, process exiting

### ISSUE THREAD

**Issue by YouveGotMeowxy** [dperson/openvpn-client#412]
I'm trying to get this up and running and not the best with this stuff. So far I can sort of get it running, but it's exiting for some reason; can anyone point out what's wrong?

```
Dump terminated
+ exec sg vpn -c 'openvpn --cd /vpn --config /vpn/vpn.conf --script-security 2 --redirect-gateway def1 --auth-user-pass /vpn/vpn.auth                 '
Sun Oct 23 12:37:02 2022 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
Sun Oct 23 12:37:02 2022 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
Sun Oct 23 12:37:02 2022 TCP/UDP: Preserving recently used remote address: [AF_INET]23.105.32.243:1194
Sun Oct 23 12:37:02 2022 Socket Buffers: R=[212992->212992] S=[212992->212992]
Sun Oct 23 12:37:02 2022 UDP link local: (not bound)
Sun Oct 23 12:37:02 2022 UDP link remote: [AF_INET]23.105.32.243:1194
Sun Oct 23 12:37:02 2022 TLS: Initial packet from [AF_INET]23.105.32.243:1194, sid=324324 5654654
Sun Oct 23 12:37:02 2022 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sun Oct 23 12:37:02 2022 VERIFY OK: depth=1, CN=Privado
Sun Oct 23 12:37:02 2022 VERIFY X509NAME OK: CN=dfw-001.vpn.privado.io
Sun Oct 23 12:37:02 2022 VERIFY OK: depth=0, CN=dfw-001.vpn.privado.io
Sun Oct 23 12:37:02 2022 Control Channel: TLSv1.2, cipher SSLv3 DHE-RSA-AES256-SHA, 4096 bit RSA
Sun Oct 23 12:37:02 2022 [dfw-001.vpn.privado.io] Peer Connection Initiated with [AF_INET]23.105.32.243:1194
Sun Oct 23 12:37:04 2022 SENT CONTROL [dfw-001.vpn.privado.io]: 'PUSH_REQUEST' (status=1)
Sun Oct 23 12:37:04 2022 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1 bypass-dhcp,dhcp-option DNS 198.18.0.1,dhcp-option DNS 198.18.0.2,rcvbuf 493216,sndbuf 493216,explicit-exit-notify 5,route-gateway 172.21.34.1,topology subnet,ping 20,ping-restart 40,ifconfig 172.21.34.107 255.255.254.0,peer-id 3,cipher AES-256-GCM'
Sun Oct 23 12:37:04 2022 OPTIONS IMPORT: timers and/or timeouts modified
Sun Oct 23 12:37:04 2022 OPTIONS IMPORT: explicit notify parm(s) modified
Sun Oct 23 12:37:04 2022 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Sun Oct 23 12:37:04 2022 Socket Buffers: R=[212992->425984] S=[212992->425984]
Sun Oct 23 12:37:04 2022 OPTIONS IMPORT: --ifconfig/up options modified
Sun Oct 23 12:37:04 2022 OPTIONS IMPORT: route options modified
Sun Oct 23 12:37:04 2022 OPTIONS IMPORT: route-related options modified
Sun Oct 23 12:37:04 2022 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Sun Oct 23 12:37:04 2022 OPTIONS IMPORT: peer-id set
Sun Oct 23 12:37:04 2022 OPTIONS IMPORT: adjusting link_mtu to 1624
Sun Oct 23 12:37:04 2022 OPTIONS IMPORT: data channel crypto options modified
Sun Oct 23 12:37:04 2022 Data Channel: using negotiated cipher 'AES-256-GCM'
Sun Oct 23 12:37:04 2022 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sun Oct 23 12:37:04 2022 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sun Oct 23 12:37:04 2022 ROUTE_GATEWAY 172.18.0.1/255.255.0.0 IFACE=eth1 HWADDR=12:34:56:78:00:43
Sun Oct 23 12:37:04 2022 TUN/TAP device tun0 opened
Sun Oct 23 12:37:04 2022 TUN/TAP TX queue length set to 100
Sun Oct 23 12:37:04 2022 /sbin/ip link set dev tun0 up mtu 1500
Sun Oct 23 12:37:04 2022 /sbin/ip addr add dev tun0 172.21.34.107/23 broadcast 172.21.35.255
Sun Oct 23 12:37:04 2022 /sbin/ip route add 23.105.32.243/32 via 172.18.0.1
Sun Oct 23 12:37:04 2022 /sbin/ip route add 0.0.0.0/1 via 172.21.34.1
Sun Oct 23 12:37:04 2022 /sbin/ip route add 128.0.0.0/1 via 172.21.34.1
Sun Oct 23 12:37:04 2022 Initialization Sequence Completed
Sun Oct 23 12:38:17 2022 event_wait : Interrupted system call (code=4)
Sun Oct 23 12:38:17 2022 SIGTERM received, sending exit notification to peer
Sun Oct 23 12:38:22 2022 /sbin/ip route del 23.105.32.243/32
Sun Oct 23 12:38:22 2022 /sbin/ip route del 0.0.0.0/1
Sun Oct 23 12:38:22 2022 /sbin/ip route del 128.0.0.0/1
Sun Oct 23 12:38:22 2022 Closing TUN/TAP interface
Sun Oct 23 12:38:22 2022 /sbin/ip addr del dev tun0 172.21.34.107/23
Sun Oct 23 12:38:22 2022 SIGTERM[soft,exit-with-notification] received, process exiting
```

<details>
  <summary>My Compose</summary>
  
```
  vpn:
    hostname: 'vpn'
    image: 'dperson/openvpn-client:latest'
    environment:
      TZ: 'America/Chicago'
      VPN_AUTH: re:dacted'
    #read_only: true
    volumes:
      - '/opt/docker/configs/openvpn/profiles:/vpn:rw'
      - '/dev/net:/dev/net:z'
    security_opt:
      - 'label:disable'
    stdin_open: true
    tty: true
    devices:
      - '/dev/net/tun:/dev/net/tun'
    cap_add:
      - 'NET_ADMIN'
    tmpfs:
      - '/run'
      - '/tmp'
    networks:
      - 'download'
    deploy:
      mode: 'replicated'
      replicas: 1
      placement:
        constraints:
          - 'node.labelsMain == true'
      resources:
        limits:
          memory: '300M'
      restart_policy:
        condition: 'any'
```
</details>

<details>
  <summary>vpn.conf</summary>

 ```
client
dev tun
proto udp
remote dfw-001.vpn.privado.io 1194
resolv-retry infinite
nobind
persist-key
persist-tun
persist-remote-ip
verify-x509-name dfw-001.vpn.privado.io name
auth-user-pass
#comp-lzo
verb 3
auth SHA256
cipher AES-256-CBC
tls-cipher TLS-DHE-RSA-WITH-AES-256-CBC-SHA:TLS-DHE-DSS-WITH-AES-256-CBC-SHA:TLS-RSA-WITH-AES-256-CBC-SHA
keepalive 10 60

<ca>
-----BEGIN CERTIFICATE-----
redacted
-----END CERTIFICATE-----
</ca>
``` 
</details>
