### ISSUE TITLE
Container unhealthy and working intermittently

### ISSUE THREAD

**Issue by BlaiseLebreton** [dperson/openvpn-client#413]
Hello ! 

Using the following docker-compose : 

```
version: "3.4"
services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z # tun device
      - ${ROOT}/config/vpn:/vpn # OpenVPN configuration
    security_opt:
      - label:disable
    command: '-f "" -r 192.168.1.0/24' # enable firewall and route local network traffic
```

I'm having mixed results. Sometimes it works perfectly for a few days and then for some reasons it stops working for another few days.

The logs are here : [_vpn_logs.txt](https://github.com/dperson/openvpn-client/files/9931385/_vpn_logs.txt)

The container is marked as unhealthy : `curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.ipify.org:443`

However I can curl the api without https :
![image](https://user-images.githubusercontent.com/59114761/199786121-8c783022-b7e6-48a5-b3f1-d2c946fdc21f.png)

Any idea what is happening ?
