### ISSUE TITLE
MacOX has no tun device

### ISSUE THREAD

**Issue by RoosterKelly** [dperson/openvpn-client#44]
The run command has `--device /dev/net/tun` in it but on MacOS there is no `/dev/net/tun` or any other `tun` device for that matter. How can this container be run on a mac?

**Comment by dperson** [comment]
OSX/macOS also doesn't really run docker natively, it still runs a Linux VM (https://docs.docker.com/engine/installation/mac/ xhyve is the FreeBSD bhyve VM software ported to OSX). So what strange gyrations they go through so that you can share files etc from your Mac into containers, or how that affects you. Or how to share a device from the Linux VM into the containers, that's past being an issue with my container.

You're going to  have to read their docs to even see if they made that possible... https://docs.docker.com/docker-for-mac/ And/Or follow up with the docker support folks.

**Comment by codethought** [comment]
@RoosterKelly - just define it as a device.. that worked for me... 

```
services:
  vpn:
    image: dperson/openvpn-client
    # cap_add, security_opt, and volume required for the image to function
    container_name: vpn
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
     # mac os doesn't have it but that doesn't mean you can't make it exist
    environment:
      TZ: 'PST8PDT'
    networks:
      - default
    # if using '-d' or 'DNS' you can't enable the `read_only: true` option
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - /Volumes/userdata/nordie:/vpn:z # Mount the directory with the .ovpn file and credentials
    ports:
      - "10022:10022"  # Example for exposing a port through the VPN
    command: "-f /vpn/foobar.ovpn"
```
