### ISSUE TITLE
VPN connection sharing to LAN computer

### ISSUE THREAD

**Issue by tibouh** [dperson/openvpn-client#48]
Hi David,

I'm planning to try this openvpn-client to give VPN access to other docker container(s).

Moreover, as I would have a working VPN connection, I was thinking of allowing other computer(s) on the LAN to use this connection.
I have googled a lot on this but have not found any tutorial.
I have to say I does not know much about docker networking so maybe this is not possible at all.
My idea is to use my server (the one hosting docker) as a gateway for computers wanting to use the VPN and then redirect this LAN traffic to the VPN container.
Would that involve some iptables routing or is it possible to use another container as proxy or something like that? I would prefer avoiding custom routing. The container solution would be great.

Thank you for your help.

Thibault

**Comment by dperson** [comment]
That's a little beyond the scope of this container itself... it just connects to a VPN, for other containers and their services. One of those could be a proxy service. Make sure you look at the `-r` (return route) option to the openvpn entrypoint script.

**Comment by jacob-pro** [comment]
I know this is a bit old, but just in case anyone wants to know how to do this:

```
version: '3.7'
services:
    openvpn:
        image: dperson/openvpn-client:latest
        devices:
            - "/dev/net/tun"
        cap_add:
            - NET_ADMIN
        volumes:
            - ./conf.ovpn:/vpn/conf.ovpn
            - ./pass.txt:/vpn/pass.txt
            - ./routing.sh:/routing.sh:ro
        networks:
            default:
            vlan36:
                ipv4_address: 10.2.36.254
        entrypoint: "/sbin/tini -- /routing.sh eth1"
    dhcp:
        image: networkboot/dhcpd
        volumes:
            - ./dhcpd.conf:/data/dhcpd.conf:ro
        network_mode: "service:openvpn"
networks:
    vlan36:
        driver: macvlan
        driver_opts:
            parent: eth1
        ipam:
            config:
                - subnet: 10.2.36.0/24
```
routing.sh
```
    #!/usr/bin/env bash

    if [ $# -ne 1 ]
    then
        echo "Usage: $(basename $0) INTERFACE"
        exit 1
    fi

    echo "Routing from $1 to tun0"
    iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE
    iptables -A FORWARD -i tun0 -o $1 -m state --state RELATED,ESTABLISHED -j ACCEPT
    iptables -A FORWARD -i $1 -o tun0 -j ACCEPT

    exec /usr/bin/openvpn.sh
```
This will forward all traffic arriving at eth1 on the docker host to the VPN. 
Just set your default gateway to point to 10.2.36.254
