### ISSUE TITLE
default route is broken?

### ISSUE THREAD

**Issue by vladshved** [dperson/openvpn-client#98]
Is it just me or default route is messed up? After openvpn comes online, default is via eth0 instead of tun0.

Kernel: 4.9.30-2+deb9u5
docker version:
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:48 2017
 OS/Arch:      linux/amd64
 Experimental: false

docker-compose.yml

```
services:
  openvpn:
    image: dperson/openvpn-client
    container_name: vpn
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    dns:
      - 8.8.4.4
      - 8.8.8.8
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - ${basepath}/config/vpn:/vpn
    environment:
      - FIREWALL=y
    healthcheck:
      test: ping -c 1 -W 3 google.com
      interval: 11s
      timeout: 10s
      retries: 5
```
